<a href="https://colab.research.google.com/github/idoschw3/Corpus2GeoRAG/blob/main/ApplyNER/NER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import pipeline
from google.colab import userdata
import pandas as pd
import numpy as np
import subprocess
import math
import json
import os

### Clone Corpus2GeoRAG Repository

In [ ]:
%%bash
rm -rf Corpus2GeoRAG
git clone https://github.com/EtzionR/Corpus2GeoRAG.git

Cloning into 'Corpus2GeoRAG'...

### Data Loading and Initial Inspection

**Purpose:** To load the raw text data, which is crucial for subsequent NER tasks, from a JSON file. This section also includes an example to visually inspect the structure and content of a single entry, ensuring the data is correctly loaded and accessible.


**Input/Output:** Input is `/content/Corpus2GeoRAG/examples/DATA.json`.

**Date:** 2026-09-23

In [ ]:
PATH = r'/content/Corpus2GeoRAG/examples/DATA.json'
PATH

'/content/Corpus2GeoRAG/examples/DATA.json'

In [ ]:
with open(PATH, 'r') as file:
    data = json.load(file)

len(data)

897

In [ ]:
[*data.keys()][:10]

['12 (song)',
 '14 May 2026 Russian strikes on Ukraine',
 '15th BRICS summit',
 '16 March 2022 Chernihiv breadline attack',
 '17 November 2024 Russian strikes on Ukraine',
 '18 March 2022 Mykolaiv military quarters attack',
 '1st European Political Community Summit',
 '2000 Meters to Andriivka',
 '2014 pro-Russian unrest in Ukraine',
 '2020s European re-armament']

In [ ]:
example = np.random.choice([*data],1)[0]


print(f'PAGE: {example}:\n\n{data[example]}')

PAGE: Ukraine's Peace Formula:

The Ukraine's Peace Formula is an initiative and diplomatic platform that Ukraine proposed to the world community to achieve a just conclusion to the Russo-Ukrainian war.


== History ==
In September 2022 Ukrainian President Volodymyr Zelenskyy addressed the UN General Assembly in a pre-recorded speech that focused on five preconditions for peace formula. There were punishment for aggression, protection of life, restoration of security and territorial integrity, security guarantees and determination to defend oneself.
On 15 November 2022 during the G20 Bali Summit Zelenskyy announced the detailed contents of the 10-point "peace formula".


== Proposals ==
The November 2022 Ukrainian proposal consists of 10 points, as reported by Ukrainian authorities and by media:

Nuclear safety, especially that of the Zaporizhzhia nuclear power plant
Food security for Asian and African countries
Energy security and restoration of Ukraine's energy infrastructure
Release of all prisoners and the return of Ukrainian children deported to Russia
Restoration of the Russia–Ukraine border to that prior to the 2014 annexation of Crimea, in line with Article 2 of the Charter of the United Nations
Full withdrawal of Russian military forces from Ukraine and cessation of hostilities
Prosecution of war crimes in the Russian invasion of Ukraine, including the creation of a special tribunal for Russian war crimes
Assessment of ecological damage, including that caused by the destruction of the Kakhovka Dam; prosecution of those responsible; recovery and reconstruction
Guarantees against future Russian aggression
A multilateral peace conference with a legally binding international treaty.


== Evaluations ==
Foreign minister of Russia Sergei Lavrov said: "It is completely not feasible. It is not possible to implement this."
U.S. President Joe Biden: "We're going to continue to support Ukraine's diplomatic effort to deliver a just and lasting peace".
French President Emmanuel Macron: "The plan ... is an essential basis for discussions on this path, which should lead us towards an international peace conference".
Secretary General of NATO Jens Stoltenberg: "Ukraine needs a just and sustainable peace, and I therefore strongly welcome President Zelenskyy's ten-point plan to achieve that goal."
President Zelenskyy noted that the Ukrainian peace formula can become a universal basis for ending other military conflicts on the planet and overcoming global problems.


== Diplomatic meetings ==
The Ukrainian peace formula was discussed at the following international meetings (Russia was not invited).
A meeting was held on 24 June 2023 in Copenhagen, Denmark, between national security advisers and representatives from Ukraine, United States, European Union, United Kingdom, Denmark, Brazil, India, Italy, Canada, Germany, South Africa, Saudi Arabia, Turkey, France, Japan and other countries.
A meeting was held on 5–6 August 2023 in Jeddah, Saudi Arabia – between 42 representatives of Western countries as well as Brazil, Egypt, India, Indonesia, South Africa, South Korea and China.
A meeting was held on 28–29 October 2023 in Valletta, Malta – between 66 representatives from the West and Global South. Among the new participants were Armenia, Holy See and Mexico.
At the meeting in Malta, the participants adopted a document in which they confirmed their intention to convene a Global Summit at the level of leaders of the countries participating in the Peace Formula, at which all provisions of the Ukrainian Peace Formula are expected to be approved by state leaders.
On 1 December 2023 in Kyiv, the tenth working meeting with representatives of 83 states and three international organizations on the implementation of the peace formula was held in Kyiv. On the Ukrainian side, the event was attended by: Minister of Defense Rustem Umierov, Minister of Justice Denys Maliuska, Deputy Speaker of the Verkhovna Rada Olena Kondratiuk, Leader of the Crimean Tatar People, People's Deputy Mustafa Dzhemilev, Nobel Peace Prize laureate, human rights activist Oleksandra Matviichuk, Head of the Office of the President of Ukraine Andriy Yermak.
United24 ambassador Richard Branson addressed the participants with a motivational speech. At the meeting, the president of the international non-governmental organization of public figures The Elders, the former President of Ireland Mary Robinson and the former Secretary-General of the United Nations Ban Ki-moon made statements in which calls were made to all countries to make efforts to ensure a just peace in Ukraine based on the key principles of the UN Charter. It was also about the importance of creating a special tribunal for the crime of aggression.


== Global Peace Summit ==

Deputy Head of the Office of the President of Ukraine Igor Zhovkva said that the 10-point peace plan would be discussed at a global summit of world leaders that could take place in early 2024. In April 2024, Swiss leaders confirmed that a high-level June 2024 Ukraine peace conference would be held.
In December 2025, Zelensky met UK Prime Minister Keir Starmer, French President Emmanuel Macron, and German Chancellor Friedrich Merz in Downing Street to discuss Ukraine's newly drafted peace plan from Ukraine–US talks in Florida.


== See also ==
Peace negotiations in the Russo-Ukrainian war (2022–present)
China's Position on the Political Settlement of the Ukrainian Crisis – 2023 position paper on Russo-Ukrainian war
Multinational Force–Ukraine – Proposed force for peace enforcementPages displaying short descriptions of redirect targets
Victory Plan for Ukraine – Peace plan for Ukraine proposed in October 2024


== References ==

In [ ]:
TITLE = '=='
MIN_LENGTH = 5

paragraphs = data[example].split('\n')
paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]

print(f'{len(paragraphs_processed)} Paragraphs Extracted from {len(paragraphs)}\n{round(len(paragraphs_processed)/len(paragraphs)*100,1)}%')

32 Paragraphs Extracted from 55
58.2%

### Text Preprocessing: Paragraph Filtering

**Purpose:** To perform an initial cleaning of the raw text by filtering out structural elements and short, uninformative lines. This step aims to prepare cleaner text segments for downstream NER processing by removing elements such as section titles and empty or minimal lines.

**Date:** 2026-09-24

In [ ]:
TITLE = '=='
MIN_LENGTH = 5

data_processed = {}

total_paragraphs = 0
total_processed = 0

for key, text in data.items():
  paragraphs = text.split('\n')
  paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]
  data_processed[key] = paragraphs_processed

  total_paragraphs += len(paragraphs)
  total_processed += len(paragraphs_processed)

print(f'{total_processed} paragraphs extracted from {total_paragraphs}\n {round(total_processed/total_paragraphs*100,1)}%')

42822 paragraphs extracted from 88029
 48.6%

In [ ]:
example = np.random.choice([*data_processed],1)[0]

print(f'PAGE: {example}:\n\n{data_processed[example]}')

PAGE: Ukrainian cultural heritage during the 2022 Russian invasion:


In [ ]:
SAVE_PATH = '/content/Corpus2GeoRAG/ApplyNER/data_initial_cleaning.json'

with open(SAVE_PATH, 'w', encoding='utf-8') as f:
    json.dump(data_processed, f, ensure_ascii=False, indent=2)

print(f'Saved to: {SAVE_PATH}')

Saved to: /content/Corpus2GeoRAG/ApplyNER/data_initial_cleaning.json

## Initial NER application

**Purpose:** To perform an initial NER application with base models and analyze the results

**Date:** 2026-09-24

### example

#### DistilBERT

In [ ]:
MODEL_DistilBERT = "dslim/distilbert-NER"
MODEL_DistilBERT

ner_DistilBERT = pipeline("ner",
               model=MODEL_DistilBERT,
               aggregation_strategy='average')

ner_DistilBERT

config.json:   0%|          | 0.00/926 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B /  261MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.20k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/669k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

TokenClassificationPipeline: {'model': 'DistilBertForTokenClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
output_DistilBERT = ner_DistilBERT(data_processed[example])
output_DistilBERT

[[{'entity_group': 'LOC',
   'score': np.float32(0.9989077),
   'word': 'Russia',
   'start': 0,
   'end': 6},
  {'entity_group': 'LOC',
   'score': np.float32(0.9986571),
   'word': 'Ukraine',
   'start': 40,
   'end': 47},
  {'entity_group': 'MISC',
   'score': np.float32(0.99675876),
   'word': 'Russo',
   'start': 98,
   'end': 103},
  {'entity_group': 'MISC',
   'score': np.float32(0.9954928),
   'word': '-',
   'start': 103,
   'end': 104},
  {'entity_group': 'MISC',
   'score': np.float32(0.9332204),
   'word': 'Ukrainian War',
   'start': 104,
   'end': 117},
  {'entity_group': 'LOC',
   'score': np.float32(0.9977196),
   'word': 'Europe',
   'start': 175,
   'end': 181},
  {'entity_group': 'MISC',
   'score': np.float32(0.983453),
   'word': 'World War II',
   'start': 188,
   'end': 200},
  {'entity_group': 'MISC',
   'score': np.float32(0.99722725),
   'word': 'Ukrainian',
   'start': 238,
   'end': 247},
  {'entity_group': 'MISC',
   'score': np.float32(0.99638414),
   'word': 'Ukrainian',
   'start': 419,
   'end': 428},
  {'entity_group': 'LOC',
   'score': np.float32(0.9989207),
   'word': 'Ukraine',
   'start': 508,
   'end': 515},
  {'entity_group': 'ORG',
   'score': np.float32(0.78767717),
   'word': 'Culture',
   'start': 530,
   'end': 537}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9567628),
   'word': 'Geneva Convention',
   'start': 108,
   'end': 125},
  {'entity_group': 'MISC',
   'score': np.float32(0.8948066),
   'word': 'Hague Convention for the Protection of Cultural Property',
   'start': 134,
   'end': 190},
  {'entity_group': 'MISC',
   'score': np.float32(0.97196317),
   'word': 'Event of Armed Conflict',
   'start': 198,
   'end': 221},
  {'entity_group': 'LOC',
   'score': np.float32(0.9963399),
   'word': 'Ukraine',
   'start': 243,
   'end': 250},
  {'entity_group': 'LOC',
   'score': np.float32(0.9982913),
   'word': 'Russia',
   'start': 255,
   'end': 261},
  {'entity_group': 'MISC',
   'score': np.float32(0.95398927),
   'word': 'Hague Convention',
   'start': 451,
   'end': 467},
  {'entity_group': 'ORG',
   'score': np.float32(0.87312824),
   'word': 'International Criminal Court',
   'start': 679,
   'end': 707}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99887997),
   'word': 'Ukraine',
   'start': 23,
   'end': 30},
  {'entity_group': 'ORG',
   'score': np.float32(0.8194624),
   'word': 'United Nation Educational, Scientific, and Cultural',
   'start': 41,
   'end': 92},
  {'entity_group': 'MISC',
   'score': np.float32(0.5466593),
   'word': 'Organization',
   'start': 93,
   'end': 105},
  {'entity_group': 'MISC',
   'score': np.float32(0.5069771),
   'word': 'UNESCO',
   'start': 107,
   'end': 113},
  {'entity_group': 'MISC',
   'score': np.float32(0.95557356),
   'word': 'World Heritage Sites',
   'start': 115,
   'end': 135},
  {'entity_group': 'LOC',
   'score': np.float32(0.9418421),
   'word': 'St',
   'start': 151,
   'end': 153},
  {'entity_group': 'LOC',
   'score': np.float32(0.89409447),
   'word': '. Sophia Cathedral',
   'start': 153,
   'end': 171},
  {'entity_group': 'LOC',
   'score': np.float32(0.99091196),
   'word': 'Kyiv',
   'start': 175,
   'end': 179},
  {'entity_group': 'LOC',
   'score': np.float32(0.83453417),
   'word': 'Kyiv',
   'start': 185,
   'end': 189},
  {'entity_group': 'LOC',
   'score': np.float32(0.79936975),
   'word': '-',
   'start': 189,
   'end': 190},
  {'entity_group': 'LOC',
   'score': np.float32(0.87279934),
   'word': 'Pechersk Lavra',
   'start': 190,
   'end': 204},
  {'entity_group': 'LOC',
   'score': np.float32(0.7381419),
   'word': 'Historic Center of Lviv',
   'start': 214,
   'end': 237},
  {'entity_group': 'LOC',
   'score': np.float32(0.9956183),
   'word': 'Kharkiv',
   'start': 259,
   'end': 266},
  {'entity_group': 'LOC',
   'score': np.float32(0.9854431),
   'word': 'Derzhprom',
   'start': 268,
   'end': 277},
  {'entity_group': 'LOC',
   'score': np.float32(0.9908086),
   'word': 'Mykolaiv',
   'start': 280,
   'end': 288},
  {'entity_group': 'LOC',
   'score': np.float32(0.7710604),
   'word': 'Observatory',
   'start': 290,
   'end': 301},
  {'entity_group': 'LOC',
   'score': np.float32(0.99051553),
   'word': 'Chernihiv',
   'start': 307,
   'end': 316},
  {'entity_group': 'LOC',
   'score': np.float32(0.9633755),
   'word': 'Transfiguration',
   'start': 318,
   'end': 333},
  {'entity_group': 'LOC',
   'score': np.float32(0.5662775),
   'word': 'Boris',
   'start': 338,
   'end': 343},
  {'entity_group': 'ORG',
   'score': np.float32(0.49886099),
   'word': 'Gleb',
   'start': 348,
   'end': 352}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9986828),
   'word': 'Politico',
   'start': 20,
   'end': 28},
  {'entity_group': 'LOC',
   'score': np.float32(0.99908483),
   'word': 'Ukraine',
   'start': 43,
   'end': 50},
  {'entity_group': 'MISC',
   'score': np.float32(0.9982749),
   'word': 'Russian',
   'start': 87,
   'end': 94},
  {'entity_group': 'ORG',
   'score': np.float32(0.9156094),
   'word': 'Moskva',
   'start': 103,
   'end': 109}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.68067735),
   'word': 'National Museum of the History of Ukraine',
   'start': 20,
   'end': 61},
  {'entity_group': 'LOC',
   'score': np.float32(0.98696494),
   'word': 'Kyiv',
   'start': 65,
   'end': 69},
  {'entity_group': 'PER',
   'score': np.float32(0.9990747),
   'word': 'Fedir Androshchuk',
   'start': 71,
   'end': 88},
  {'entity_group': 'PER',
   'score': np.float32(0.90752006),
   'word': 'Androschuck',
   'start': 190,
   'end': 201},
  {'entity_group': 'LOC',
   'score': np.float32(0.9968208),
   'word': 'Vinnytsia',
   'start': 243,
   'end': 252},
  {'entity_group': 'LOC',
   'score': np.float32(0.9888358),
   'word': 'Zhytomyr',
   'start': 254,
   'end': 262},
  {'entity_group': 'LOC',
   'score': np.float32(0.989995),
   'word': 'Sumy',
   'start': 264,
   'end': 268},
  {'entity_group': 'LOC',
   'score': np.float32(0.9873393),
   'word': 'Chernihiv',
   'start': 273,
   'end': 282},
  {'entity_group': 'LOC',
   'score': np.float32(0.9961398),
   'word': 'Vinnytsia',
   'start': 366,
   'end': 375},
  {'entity_group': 'ORG',
   'score': np.float32(0.9468678),
   'word': 'Asortymentna',
   'start': 435,
   'end': 447},
  {'entity_group': 'ORG',
   'score': np.float32(0.7777214),
   'word': 'Assorted Room',
   'start': 457,
   'end': 470},
  {'entity_group': 'LOC',
   'score': np.float32(0.88139445),
   'word': 'Ivano',
   'start': 485,
   'end': 490},
  {'entity_group': 'LOC',
   'score': np.float32(0.89877915),
   'word': '-',
   'start': 490,
   'end': 491},
  {'entity_group': 'LOC',
   'score': np.float32(0.6625491),
   'word': 'Frankivsk Contemporary Art Center',
   'start': 491,
   'end': 524},
  {'entity_group': 'LOC',
   'score': np.float32(0.9960783),
   'word': 'Kyiv',
   'start': 579,
   'end': 583},
  {'entity_group': 'LOC',
   'score': np.float32(0.9963154),
   'word': 'Mariupol',
   'start': 585,
   'end': 593},
  {'entity_group': 'LOC',
   'score': np.float32(0.99715996),
   'word': 'Odesa',
   'start': 595,
   'end': 600},
  {'entity_group': 'LOC',
   'score': np.float32(0.99392277),
   'word': 'Zaporizhzhia',
   'start': 602,
   'end': 614}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99266773),
   'word': 'Kyiv',
   'start': 98,
   'end': 102},
  {'entity_group': 'LOC',
   'score': np.float32(0.9989761),
   'word': 'Lviv',
   'start': 186,
   'end': 190},
  {'entity_group': 'ORG',
   'score': np.float32(0.89511234),
   'word': 'Lviv Foundation for the Preservation of Architectural and Historical',
   'start': 394,
   'end': 462}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.665867),
   'word': 'NFT',
   'start': 15,
   'end': 18},
  {'entity_group': 'ORG',
   'score': np.float32(0.97291875),
   'word': 'Ministry of Digital Transformation',
   'start': 42,
   'end': 76},
  {'entity_group': 'LOC',
   'score': np.float32(0.99722385),
   'word': 'Ukraine',
   'start': 123,
   'end': 130},
  {'entity_group': 'MISC',
   'score': np.float32(0.9133494),
   'word': 'Ukrainian',
   'start': 183,
   'end': 192},
  {'entity_group': 'ORG',
   'score': np.float32(0.6183748),
   'word': 'MetaHistory',
   'start': 193,
   'end': 204},
  {'entity_group': 'MISC',
   'score': np.float32(0.3942403),
   'word': 'NFT - Museum',
   'start': 205,
   'end': 215},
  {'entity_group': 'MISC',
   'score': np.float32(0.64556575),
   'word': 'NFT',
   'start': 286,
   'end': 289},
  {'entity_group': 'MISC',
   'score': np.float32(0.9971691),
   'word': 'Ukrainian',
   'start': 386,
   'end': 395},
  {'entity_group': 'MISC',
   'score': np.float32(0.53230554),
   'word': 'NFTs',
   'start': 471,
   'end': 475}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99863607),
   'word': 'Ukraine',
   'start': 53,
   'end': 60},
  {'entity_group': 'MISC',
   'score': np.float32(0.99565494),
   'word': 'Russian',
   'start': 66,
   'end': 73},
  {'entity_group': 'MISC',
   'score': np.float32(0.9974158),
   'word': 'Russian',
   'start': 98,
   'end': 105}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9970415),
   'word': 'UNESCO',
   'start': 28,
   'end': 34},
  {'entity_group': 'MISC',
   'score': np.float32(0.9489155),
   'word': 'Hague Convention',
   'start': 169,
   'end': 185},
  {'entity_group': 'ORG',
   'score': np.float32(0.99385613),
   'word': 'International Council of Museums',
   'start': 529,
   'end': 561}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99792093),
   'word': 'Poland',
   'start': 25,
   'end': 31},
  {'entity_group': 'ORG',
   'score': np.float32(0.7979576),
   'word': 'Committee for Aid to Museums of Ukraine',
   'start': 57,
   'end': 96},
  {'entity_group': 'LOC',
   'score': np.float32(0.998681),
   'word': 'Ukraine',
   'start': 207,
   'end': 214},
  {'entity_group': 'ORG',
   'score': np.float32(0.9728465),
   'word': 'Czech Ministry of Culture',
   'start': 404,
   'end': 429},
  {'entity_group': 'ORG',
   'score': np.float32(0.9410025),
   'word': 'National Museum of Prague',
   'start': 447,
   'end': 472},
  {'entity_group': 'ORG',
   'score': np.float32(0.9952144),
   'word': 'Ukraine Art Aid Center',
   'start': 681,
   'end': 703},
  {'entity_group': 'LOC',
   'score': np.float32(0.9984701),
   'word': 'Germany',
   'start': 714,
   'end': 721},
  {'entity_group': 'MISC',
   'score': np.float32(0.99801946),
   'word': 'German',
   'start': 740,
   'end': 746},
  {'entity_group': 'ORG',
   'score': np.float32(0.99885863),
   'word': 'ALIPH',
   'start': 777,
   'end': 782},
  {'entity_group': 'LOC',
   'score': np.float32(0.9982014),
   'word': 'Switzerland',
   'start': 793,
   'end': 804}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9987758),
   'word': 'Ukraine',
   'start': 95,
   'end': 102},
  {'entity_group': 'MISC',
   'score': np.float32(0.58209676),
   'word': 'Ukrainian',
   'start': 143,
   'end': 152},
  {'entity_group': 'ORG',
   'score': np.float32(0.7175178),
   'word': 'Cultural Heritage Online',
   'start': 153,
   'end': 177},
  {'entity_group': 'ORG',
   'score': np.float32(0.98410857),
   'word': 'SUCHO',
   'start': 179,
   'end': 184}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.99493235),
   'word': 'European Commission',
   'start': 42,
   'end': 61},
  {'entity_group': 'MISC',
   'score': np.float32(0.9944543),
   'word': 'Ukrainian',
   'start': 160,
   'end': 169},
  {'entity_group': 'ORG',
   'score': np.float32(0.99507827),
   'word': 'European Union',
   'start': 183,
   'end': 197},
  {'entity_group': 'LOC',
   'score': np.float32(0.99804497),
   'word': 'Ukraine',
   'start': 270,
   'end': 277}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9992034),
   'word': 'Japan',
   'start': 18,
   'end': 23},
  {'entity_group': 'LOC',
   'score': np.float32(0.99915004),
   'word': 'Ukraine',
   'start': 75,
   'end': 82},
  {'entity_group': 'LOC',
   'score': np.float32(0.9966407),
   'word': 'Kyiv',
   'start': 169,
   'end': 173},
  {'entity_group': 'MISC',
   'score': np.float32(0.9981236),
   'word': 'Japanese',
   'start': 182,
   'end': 190},
  {'entity_group': 'PER',
   'score': np.float32(0.99811006),
   'word': 'Nakagome Masashi',
   'start': 202,
   'end': 218},
  {'entity_group': 'MISC',
   'score': np.float32(0.9955403),
   'word': 'Ukrainian',
   'start': 220,
   'end': 229},
  {'entity_group': 'ORG',
   'score': np.float32(0.99030685),
   'word': 'UNESCO',
   'start': 264,
   'end': 270}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.80309814),
   'word': 'Ukrainian Cultural Center',
   'start': 4,
   'end': 29},
  {'entity_group': 'LOC',
   'score': np.float32(0.99652433),
   'word': 'East Hollywood',
   'start': 33,
   'end': 47},
  {'entity_group': 'LOC',
   'score': np.float32(0.9918213),
   'word': 'Los Angeles',
   'start': 49,
   'end': 60},
  {'entity_group': 'LOC',
   'score': np.float32(0.9928803),
   'word': 'California',
   'start': 62,
   'end': 72},
  {'entity_group': 'MISC',
   'score': np.float32(0.9960514),
   'word': 'Ukrainian',
   'start': 126,
   'end': 135},
  {'entity_group': 'LOC',
   'score': np.float32(0.9985846),
   'word': 'LA',
   'start': 147,
   'end': 149},
  {'entity_group': 'PER',
   'score': np.float32(0.9988644),
   'word': 'Myroslav Skoryk',
   'start': 241,
   'end': 256},
  {'entity_group': 'LOC',
   'score': np.float32(0.99867034),
   'word': 'Ukraine',
   'start': 338,
   'end': 345},
  {'entity_group': 'LOC',
   'score': np.float32(0.9988902),
   'word': 'Ukraine',
   'start': 555,
   'end': 562}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.993997),
   'word': 'Milan',
   'start': 9,
   'end': 14},
  {'entity_group': 'MISC',
   'score': np.float32(0.99500173),
   'word': 'Ukrainian',
   'start': 44,
   'end': 53},
  {'entity_group': 'PER',
   'score': np.float32(0.9989089),
   'word': 'Victoria Yakusha',
   'start': 64,
   'end': 80},
  {'entity_group': 'PER',
   'score': np.float32(0.9988906),
   'word': 'Kateryna Sokolova',
   'start': 85,
   'end': 102},
  {'entity_group': 'LOC',
   'score': np.float32(0.9964361),
   'word': 'Ukraine',
   'start': 156,
   'end': 163},
  {'entity_group': 'PER',
   'score': np.float32(0.99863505),
   'word': 'Sokolova',
   'start': 183,
   'end': 191},
  {'entity_group': 'MISC',
   'score': np.float32(0.99713945),
   'word': 'Ukrainian',
   'start': 246,
   'end': 255},
  {'entity_group': 'PER',
   'score': np.float32(0.99873775),
   'word': 'Yakusha',
   'start': 300,
   'end': 307},
  {'entity_group': 'MISC',
   'score': np.float32(0.99680305),
   'word': 'Ukrainian',
   'start': 378,
   'end': 387}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.7413751),
   'word': 'Backup Ukraine',
   'start': 4,
   'end': 18},
  {'entity_group': 'ORG',
   'score': np.float32(0.99306333),
   'word': 'Virtue Media Group VICE',
   'start': 47,
   'end': 70},
  {'entity_group': 'ORG',
   'score': np.float32(0.99570346),
   'word': 'Blue Shield Danmark',
   'start': 72,
   'end': 91},
  {'entity_group': 'ORG',
   'score': np.float32(0.98745024),
   'word': 'Danish National Commission for UNESCO',
   'start': 100,
   'end': 137},
  {'entity_group': 'LOC',
   'score': np.float32(0.99860686),
   'word': 'Ukraine',
   'start': 222,
   'end': 229}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9987684),
   'word': 'Toronto',
   'start': 24,
   'end': 31},
  {'entity_group': 'LOC',
   'score': np.float32(0.9988367),
   'word': 'Canada',
   'start': 33,
   'end': 39},
  {'entity_group': 'LOC',
   'score': np.float32(0.9953589),
   'word': 'Ukraine',
   'start': 87,
   'end': 94},
  {'entity_group': 'LOC',
   'score': np.float32(0.9223528),
   'word': 'Toronto City Hall',
   'start': 118,
   'end': 135},
  {'entity_group': 'MISC',
   'score': np.float32(0.5231193),
   'word': 'Russia',
   'start': 166,
   'end': 172},
  {'entity_group': 'MISC',
   'score': np.float32(0.9980894),
   'word': 'Ukrainian',
   'start': 176,
   'end': 185}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9812216),
   'word': 'UNESCO UNESCO',
   'start': 20,
   'end': 33}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.94157344),
   'word': 'Ministry of Culture of Ukraine',
   'start': 0,
   'end': 30},
  {'entity_group': 'ORG',
   'score': np.float32(0.86999106),
   'word': 'Cultural Heritage Monitoring Lab',
   'start': 394,
   'end': 426},
  {'entity_group': 'LOC',
   'score': np.float32(0.7048045),
   'word': 'Virginia Museum',
   'start': 430,
   'end': 445},
  {'entity_group': 'ORG',
   'score': np.float32(0.7249325),
   'word': 'of Natural History',
   'start': 446,
   'end': 464},
  {'entity_group': 'ORG',
   'score': np.float32(0.95880336),
   'word': 'New York Times Visual Investigations',
   'start': 534,
   'end': 570},
  {'entity_group': 'LOC',
   'score': np.float32(0.97779983),
   'word': 'Donbas',
   'start': 758,
   'end': 764}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.80593616),
   'word': 'Ivankiv Historical and Local History Museum',
   'start': 21,
   'end': 64},
  {'entity_group': 'MISC',
   'score': np.float32(0.9978611),
   'word': 'Russian',
   'start': 131,
   'end': 138},
  {'entity_group': 'PER',
   'score': np.float32(0.9986905),
   'word': 'Maria Prymachenko',
   'start': 210,
   'end': 227},
  {'entity_group': 'PER',
   'score': np.float32(0.9988526),
   'word': 'Hanna Veres',
   'start': 249,
   'end': 260},
  {'entity_group': 'PER',
   'score': np.float32(0.99095964),
   'word': 'Prymachenko',
   'start': 367,
   'end': 378},
  {'entity_group': 'PER',
   'score': np.float32(0.81928605),
   'word': 'Veres',
   'start': 380,
   'end': 385}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.6342879),
   'word': 'Babyn Yar Holocaust Memorial Center',
   'start': 4,
   'end': 39},
  {'entity_group': 'LOC',
   'score': np.float32(0.655515),
   'word': 'Kyiv Small Opera',
   'start': 298,
   'end': 314}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.83716166),
   'word': 'Dormition Cathedral',
   'start': 4,
   'end': 23},
  {'entity_group': 'LOC',
   'score': np.float32(0.9964692),
   'word': 'Kharkiv',
   'start': 27,
   'end': 34},
  {'entity_group': 'LOC',
   'score': np.float32(0.9950233),
   'word': 'Kharkiv',
   'start': 68,
   'end': 75},
  {'entity_group': 'LOC',
   'score': np.float32(0.98674095),
   'word': 'Kharkiv',
   'start': 175,
   'end': 182},
  {'entity_group': 'LOC',
   'score': np.float32(0.46188253),
   'word': 'Slovo Building',
   'start': 200,
   'end': 214},
  {'entity_group': 'LOC',
   'score': np.float32(0.9957708),
   'word': 'Kharkiv',
   'start': 218,
   'end': 225},
  {'entity_group': 'MISC',
   'score': np.float32(0.9987943),
   'word': 'Russian',
   'start': 247,
   'end': 254},
  {'entity_group': 'LOC',
   'score': np.float32(0.9895439),
   'word': 'Drobytsky Yar',
   'start': 298,
   'end': 311},
  {'entity_group': 'LOC',
   'score': np.float32(0.9969358),
   'word': 'Kharkiv',
   'start': 332,
   'end': 339},
  {'entity_group': 'MISC',
   'score': np.float32(0.9565601),
   'word': 'Holocaust',
   'start': 353,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.8684246),
   'word': 'Kharkiv Art Museum',
   'start': 404,
   'end': 422},
  {'entity_group': 'LOC',
   'score': np.float32(0.80150694),
   'word': 'Kharkiv',
   'start': 605,
   'end': 612},
  {'entity_group': 'ORG',
   'score': np.float32(0.8752325),
   'word': 'Regional Administration',
   'start': 613,
   'end': 636},
  {'entity_group': 'LOC',
   'score': np.float32(0.9027649),
   'word': 'Kharkiv',
   'start': 647,
   'end': 654},
  {'entity_group': 'ORG',
   'score': np.float32(0.67598283),
   'word': 'City Council',
   'start': 655,
   'end': 667},
  {'entity_group': 'ORG',
   'score': np.float32(0.9316633),
   'word': 'Opera & Ballet Theatre',
   'start': 673,
   'end': 695},
  {'entity_group': 'ORG',
   'score': np.float32(0.8666623),
   'word': 'Faculty of Economics',
   'start': 704,
   'end': 724},

In [ ]:
df_DistilBERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_DistilBERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,LOC,0.998908,Russia,0,6
1,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,LOC,0.998657,Ukraine,40,47
2,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,MISC,0.996759,Russo,98,103
3,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,MISC,0.995493,-,103,104
4,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,MISC,0.933220,Ukrainian War,104,117
...,...,...,...,...,...,...,...,...
394,Ukrainian cultural heritage during the 2022 Ru...,50,"Egan, Lauren (2022-05-30). ""Ukrainians see the...",LOC,0.996311,Russia,73,79
395,Ukrainian cultural heritage during the 2022 Ru...,50,"Egan, Lauren (2022-05-30). ""Ukrainians see the...",ORG,0.859922,NBC News.,101,110
396,Ukrainian cultural heritage during the 2022 Ru...,51,"""Map of cultural losses"". Ukrainian Cultural F...",ORG,0.992799,Ukrainian Cultural Foundation,26,55
397,Ukrainian cultural heritage during the 2022 Ru...,52,List of damaged objects by Ukrainian Ministry ...,MISC,0.698304,Ukrainian,27,36
398,Ukrainian cultural heritage during the 2022 Ru...,52,List of damaged objects by Ukrainian Ministry ...,ORG,0.975995,Ministry of Culture,37,56

#### BERT

In [ ]:
MODEL_BERT = "dslim/bert-base-NER"
MODEL_BERT

ner_BERT = pipeline("ner",
               model=MODEL_BERT,
               aggregation_strategy='average')

ner_BERT

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  433MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

TokenClassificationPipeline: {'model': 'BertForTokenClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
output_BERT = ner_BERT(data_processed[example])
output_BERT

[[{'entity_group': 'LOC',
   'score': np.float32(0.99982953),
   'word': 'Russia',
   'start': 0,
   'end': 6},
  {'entity_group': 'LOC',
   'score': np.float32(0.9998275),
   'word': 'Ukraine',
   'start': 40,
   'end': 47},
  {'entity_group': 'MISC',
   'score': np.float32(0.98833877),
   'word': 'Russo - Ukrainian War',
   'start': 98,
   'end': 117},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997217),
   'word': 'Europe',
   'start': 175,
   'end': 181},
  {'entity_group': 'MISC',
   'score': np.float32(0.9977885),
   'word': 'World War II',
   'start': 188,
   'end': 200},
  {'entity_group': 'MISC',
   'score': np.float32(0.9996915),
   'word': 'Ukrainian',
   'start': 238,
   'end': 247},
  {'entity_group': 'MISC',
   'score': np.float32(0.99970156),
   'word': 'Ukrainian',
   'start': 419,
   'end': 428},
  {'entity_group': 'LOC',
   'score': np.float32(0.99980074),
   'word': 'Ukraine',
   'start': 508,
   'end': 515}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9862183),
   'word': 'Geneva Convention',
   'start': 108,
   'end': 125},
  {'entity_group': 'MISC',
   'score': np.float32(0.9921296),
   'word': 'Hague Convention for the Protection of Cultural Property',
   'start': 134,
   'end': 190},
  {'entity_group': 'MISC',
   'score': np.float32(0.8827666),
   'word': 'Event of Armed Conflict',
   'start': 198,
   'end': 221},
  {'entity_group': 'LOC',
   'score': np.float32(0.99942124),
   'word': 'Ukraine',
   'start': 243,
   'end': 250},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997067),
   'word': 'Russia',
   'start': 255,
   'end': 261},
  {'entity_group': 'MISC',
   'score': np.float32(0.9743296),
   'word': 'Second Protocol',
   'start': 428,
   'end': 443},
  {'entity_group': 'MISC',
   'score': np.float32(0.9912604),
   'word': 'Hague Convention',
   'start': 451,
   'end': 467},
  {'entity_group': 'ORG',
   'score': np.float32(0.9674123),
   'word': 'International Criminal Court',
   'start': 679,
   'end': 707}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99982697),
   'word': 'Ukraine',
   'start': 23,
   'end': 30},
  {'entity_group': 'ORG',
   'score': np.float32(0.9986465),
   'word': 'United Nation Educational, Scientific, and Cultural Organization',
   'start': 41,
   'end': 105},
  {'entity_group': 'ORG',
   'score': np.float32(0.98842454),
   'word': 'UNESCO',
   'start': 107,
   'end': 113},
  {'entity_group': 'MISC',
   'score': np.float32(0.96891385),
   'word': 'World Heritage Sites',
   'start': 115,
   'end': 135},
  {'entity_group': 'LOC',
   'score': np.float32(0.98475695),
   'word': 'St. Sophia Cathedral',
   'start': 151,
   'end': 171},
  {'entity_group': 'LOC',
   'score': np.float32(0.57433385),
   'word': 'Kyiv',
   'start': 175,
   'end': 179},
  {'entity_group': 'LOC',
   'score': np.float32(0.64567304),
   'word': 'Kyiv',
   'start': 185,
   'end': 189},
  {'entity_group': 'LOC',
   'score': np.float32(0.8694117),
   'word': 'Pechersk Lavra',
   'start': 190,
   'end': 204},
  {'entity_group': 'LOC',
   'score': np.float32(0.8114929),
   'word': 'Historic Center of Lviv',
   'start': 214,
   'end': 237},
  {'entity_group': 'LOC',
   'score': np.float32(0.74740756),
   'word': 'Kharkiv',
   'start': 259,
   'end': 266},
  {'entity_group': 'LOC',
   'score': np.float32(0.7422292),
   'word': 'Derzhprom',
   'start': 268,
   'end': 277},
  {'entity_group': 'LOC',
   'score': np.float32(0.74302083),
   'word': 'Mykolaiv',
   'start': 280,
   'end': 288},
  {'entity_group': 'LOC',
   'score': np.float32(0.6960535),
   'word': 'Observatory',
   'start': 290,
   'end': 301},
  {'entity_group': 'LOC',
   'score': np.float32(0.73131126),
   'word': 'Chernihiv',
   'start': 307,
   'end': 316},
  {'entity_group': 'LOC',
   'score': np.float32(0.3035879),
   'word': 'Transfiguration',
   'start': 318,
   'end': 333},
  {'entity_group': 'LOC',
   'score': np.float32(0.7436697),
   'word': 'Boris',
   'start': 338,
   'end': 343},
  {'entity_group': 'LOC',
   'score': np.float32(0.5179414),
   'word': 'Gleb',
   'start': 348,
   'end': 352}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.66530746),
   'word': 'Politico',
   'start': 20,
   'end': 28},
  {'entity_group': 'LOC',
   'score': np.float32(0.9998242),
   'word': 'Ukraine',
   'start': 43,
   'end': 50},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997793),
   'word': 'Russian',
   'start': 87,
   'end': 94},
  {'entity_group': 'LOC',
   'score': np.float32(0.5943023),
   'word': 'Moskva',
   'start': 103,
   'end': 109}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.96842766),
   'word': 'National Museum of the History of Ukraine',
   'start': 20,
   'end': 61},
  {'entity_group': 'LOC',
   'score': np.float32(0.60486686),
   'word': 'Kyiv',
   'start': 65,
   'end': 69},
  {'entity_group': 'PER',
   'score': np.float32(0.9925004),
   'word': 'Fedir Androshchuk',
   'start': 71,
   'end': 88},
  {'entity_group': 'PER',
   'score': np.float32(0.60873973),
   'word': 'Androschuck',
   'start': 190,
   'end': 201},
  {'entity_group': 'LOC',
   'score': np.float32(0.744534),
   'word': 'Vinnytsia',
   'start': 243,
   'end': 252},
  {'entity_group': 'LOC',
   'score': np.float32(0.74308324),
   'word': 'Zhytomyr',
   'start': 254,
   'end': 262},
  {'entity_group': 'LOC',
   'score': np.float32(0.6966922),
   'word': 'Sumy',
   'start': 264,
   'end': 268},
  {'entity_group': 'LOC',
   'score': np.float32(0.53904086),
   'word': 'Chernihiv',
   'start': 273,
   'end': 282},
  {'entity_group': 'LOC',
   'score': np.float32(0.73794246),
   'word': 'Vinnytsia',
   'start': 366,
   'end': 375},
  {'entity_group': 'ORG',
   'score': np.float32(0.84128594),
   'word': 'Asortymentna kimnata',
   'start': 435,
   'end': 455},
  {'entity_group': 'ORG',
   'score': np.float32(0.94200975),
   'word': 'Room',
   'start': 466,
   'end': 470},
  {'entity_group': 'LOC',
   'score': np.float32(0.7839059),
   'word': 'Ivano - Frankivsk Contemporary',
   'start': 485,
   'end': 513},
  {'entity_group': 'ORG',
   'score': np.float32(0.6181705),
   'word': 'Art',
   'start': 514,
   'end': 517},
  {'entity_group': 'LOC',
   'score': np.float32(0.9134886),
   'word': 'Center',
   'start': 518,
   'end': 524},
  {'entity_group': 'LOC',
   'score': np.float32(0.65335095),
   'word': 'Kyiv',
   'start': 579,
   'end': 583},
  {'entity_group': 'LOC',
   'score': np.float32(0.6326118),
   'word': 'Mariupol',
   'start': 585,
   'end': 593},
  {'entity_group': 'LOC',
   'score': np.float32(0.6545606),
   'word': 'Odesa',
   'start': 595,
   'end': 600},
  {'entity_group': 'LOC',
   'score': np.float32(0.8532351),
   'word': 'Zaporizhzhia',
   'start': 602,
   'end': 614}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.5193706),
   'word': 'Kyiv',
   'start': 98,
   'end': 102},
  {'entity_group': 'LOC',
   'score': np.float32(0.9996338),
   'word': 'Lviv',
   'start': 186,
   'end': 190},
  {'entity_group': 'ORG',
   'score': np.float32(0.99119633),
   'word': 'Lviv Foundation for the Preservation of Architectural and Historical Monuments',
   'start': 394,
   'end': 472}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.4695167),
   'word': 'NFT',
   'start': 15,
   'end': 18},
  {'entity_group': 'ORG',
   'score': np.float32(0.9987144),
   'word': 'Ministry of Digital Transformation',
   'start': 42,
   'end': 76},
  {'entity_group': 'LOC',
   'score': np.float32(0.99975103),
   'word': 'Ukraine',
   'start': 123,
   'end': 130},
  {'entity_group': 'MISC',
   'score': np.float32(0.98426867),
   'word': 'Ukrainian',
   'start': 183,
   'end': 192},
  {'entity_group': 'ORG',
   'score': np.float32(0.5226641),
   'word': 'MetaHistory NFT',
   'start': 193,
   'end': 208},
  {'entity_group': 'ORG',
   'score': np.float32(0.4917787),
   'word': 'NFT',
   'start': 286,
   'end': 289},
  {'entity_group': 'MISC',
   'score': np.float32(0.9995926),
   'word': 'Ukrainian',
   'start': 386,
   'end': 395}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9998173),
   'word': 'Ukraine',
   'start': 53,
   'end': 60},
  {'entity_group': 'MISC',
   'score': np.float32(0.99972886),
   'word': 'Russian',
   'start': 66,
   'end': 73},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997545),
   'word': 'Russian',
   'start': 98,
   'end': 105}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.99914956),
   'word': 'UNESCO',
   'start': 28,
   'end': 34},
  {'entity_group': 'MISC',
   'score': np.float32(0.989946),
   'word': 'Hague Convention',
   'start': 169,
   'end': 185},
  {'entity_group': 'ORG',
   'score': np.float32(0.9980085),
   'word': 'International Council of Museums',
   'start': 529,
   'end': 561}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9997019),
   'word': 'Poland',
   'start': 25,
   'end': 31},
  {'entity_group': 'ORG',
   'score': np.float32(0.998383),
   'word': 'Committee for Aid to Museums of Ukraine',
   'start': 57,
   'end': 96},
  {'entity_group': 'ORG',
   'score': np.float32(0.99776816),
   'word': 'Committee',
   'start': 137,
   'end': 146},
  {'entity_group': 'LOC',
   'score': np.float32(0.99977916),
   'word': 'Ukraine',
   'start': 207,
   'end': 214},
  {'entity_group': 'ORG',
   'score': np.float32(0.9817748),
   'word': 'Czech Ministry of Culture',
   'start': 404,
   'end': 429},
  {'entity_group': 'ORG',
   'score': np.float32(0.97083616),
   'word': 'National Museum of Prague',
   'start': 447,
   'end': 472},
  {'entity_group': 'ORG',
   'score': np.float32(0.9963722),
   'word': 'Ukraine Art Aid Center',
   'start': 681,
   'end': 703},
  {'entity_group': 'LOC',
   'score': np.float32(0.999602),
   'word': 'Germany',
   'start': 714,
   'end': 721},
  {'entity_group': 'MISC',
   'score': np.float32(0.9995809),
   'word': 'German',
   'start': 740,
   'end': 746},
  {'entity_group': 'ORG',
   'score': np.float32(0.6653697),
   'word': 'ALIPH',
   'start': 777,
   'end': 782},
  {'entity_group': 'LOC',
   'score': np.float32(0.99975413),
   'word': 'Switzerland',
   'start': 793,
   'end': 804}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99978596),
   'word': 'Ukraine',
   'start': 95,
   'end': 102},
  {'entity_group': 'ORG',
   'score': np.float32(0.85294163),
   'word': 'Saving Ukrainian Cultural Heritage Online',
   'start': 136,
   'end': 177},
  {'entity_group': 'ORG',
   'score': np.float32(0.597676),
   'word': 'SUCHO',
   'start': 179,
   'end': 184}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9993752),
   'word': 'European Commission',
   'start': 42,
   'end': 61},
  {'entity_group': 'MISC',
   'score': np.float32(0.99969184),
   'word': 'Ukrainian',
   'start': 160,
   'end': 169},
  {'entity_group': 'ORG',
   'score': np.float32(0.99947345),
   'word': 'European Union',
   'start': 183,
   'end': 197},
  {'entity_group': 'LOC',
   'score': np.float32(0.999762),
   'word': 'Ukraine',
   'start': 270,
   'end': 277}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99984443),
   'word': 'Japan',
   'start': 18,
   'end': 23},
  {'entity_group': 'LOC',
   'score': np.float32(0.99984384),
   'word': 'Ukraine',
   'start': 75,
   'end': 82},
  {'entity_group': 'LOC',
   'score': np.float32(0.655821),
   'word': 'Kyiv',
   'start': 169,
   'end': 173},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997279),
   'word': 'Japanese',
   'start': 182,
   'end': 190},
  {'entity_group': 'PER',
   'score': np.float32(0.9036708),
   'word': 'Nakagome Masashi',
   'start': 202,
   'end': 218},
  {'entity_group': 'MISC',
   'score': np.float32(0.99970645),
   'word': 'Ukrainian',
   'start': 220,
   'end': 229},
  {'entity_group': 'ORG',
   'score': np.float32(0.99917513),
   'word': 'UNESCO',
   'start': 264,
   'end': 270}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.57107735),
   'word': 'Ukrainian',
   'start': 4,
   'end': 13},
  {'entity_group': 'LOC',
   'score': np.float32(0.938259),
   'word': 'Cultural Center',
   'start': 14,
   'end': 29},
  {'entity_group': 'LOC',
   'score': np.float32(0.9993249),
   'word': 'East Hollywood',
   'start': 33,
   'end': 47},
  {'entity_group': 'LOC',
   'score': np.float32(0.999511),
   'word': 'Los Angeles',
   'start': 49,
   'end': 60},
  {'entity_group': 'LOC',
   'score': np.float32(0.99961156),
   'word': 'California',
   'start': 62,
   'end': 72},
  {'entity_group': 'MISC',
   'score': np.float32(0.99967706),
   'word': 'Ukrainian',
   'start': 126,
   'end': 135},
  {'entity_group': 'LOC',
   'score': np.float32(0.9995875),
   'word': 'LA',
   'start': 147,
   'end': 149},
  {'entity_group': 'PER',
   'score': np.float32(0.99431574),
   'word': 'Myroslav Skoryk',
   'start': 241,
   'end': 256},
  {'entity_group': 'LOC',
   'score': np.float32(0.99980384),
   'word': 'Ukraine',
   'start': 338,
   'end': 345},
  {'entity_group': 'LOC',
   'score': np.float32(0.99975044),
   'word': 'Ukraine',
   'start': 555,
   'end': 562}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99934095),
   'word': 'Milan',
   'start': 9,
   'end': 14},
  {'entity_group': 'MISC',
   'score': np.float32(0.9996842),
   'word': 'Ukrainian',
   'start': 44,
   'end': 53},
  {'entity_group': 'PER',
   'score': np.float32(0.99911),
   'word': 'Victoria Yakusha',
   'start': 64,
   'end': 80},
  {'entity_group': 'PER',
   'score': np.float32(0.8628784),
   'word': 'Kateryna Sokolova',
   'start': 85,
   'end': 102},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997651),
   'word': 'Ukraine',
   'start': 156,
   'end': 163},
  {'entity_group': 'PER',
   'score': np.float32(0.4884233),
   'word': 'Sokolova',
   'start': 183,
   'end': 191},
  {'entity_group': 'MISC',
   'score': np.float32(0.99968696),
   'word': 'Ukrainian',
   'start': 246,
   'end': 255},
  {'entity_group': 'PER',
   'score': np.float32(0.4653201),
   'word': 'Yakusha',
   'start': 300,
   'end': 307},
  {'entity_group': 'MISC',
   'score': np.float32(0.99968565),
   'word': 'Ukrainian',
   'start': 378,
   'end': 387}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.7310275),
   'word': 'Backup Ukraine',
   'start': 4,
   'end': 18},
  {'entity_group': 'ORG',
   'score': np.float32(0.91468626),
   'word': 'Virtue Media Group VICE',
   'start': 47,
   'end': 70},
  {'entity_group': 'ORG',
   'score': np.float32(0.99809116),
   'word': 'Blue Shield Danmark',
   'start': 72,
   'end': 91},
  {'entity_group': 'ORG',
   'score': np.float32(0.9938299),
   'word': 'Danish National Commission for UNESCO',
   'start': 100,
   'end': 137},
  {'entity_group': 'LOC',
   'score': np.float32(0.9998066),
   'word': 'Ukraine',
   'start': 222,
   'end': 229},
  {'entity_group': 'MISC',
   'score': np.float32(0.55185246),
   'word': '3D',
   'start': 267,
   'end': 269}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9996289),
   'word': 'Toronto',
   'start': 24,
   'end': 31},
  {'entity_group': 'LOC',
   'score': np.float32(0.9994672),
   'word': 'Canada',
   'start': 33,
   'end': 39},
  {'entity_group': 'LOC',
   'score': np.float32(0.99854916),
   'word': 'Ukraine',
   'start': 87,
   'end': 94},
  {'entity_group': 'LOC',
   'score': np.float32(0.99699944),
   'word': 'Toronto City Hall',
   'start': 118,
   'end': 135},
  {'entity_group': 'LOC',
   'score': np.float32(0.9994419),
   'word': 'Russia',
   'start': 166,
   'end': 172},
  {'entity_group': 'MISC',
   'score': np.float32(0.99972945),
   'word': 'Ukrainian',
   'start': 176,
   'end': 185}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.91586095),
   'word': 'UNESCO UNESCO',
   'start': 20,
   'end': 33}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9982794),
   'word': 'Ministry of Culture of Ukraine',
   'start': 0,
   'end': 30},
  {'entity_group': 'ORG',
   'score': np.float32(0.99386287),
   'word': 'Cultural Heritage Monitoring Lab',
   'start': 394,
   'end': 426},
  {'entity_group': 'ORG',
   'score': np.float32(0.87965405),
   'word': 'Virginia Museum of Natural History',
   'start': 430,
   'end': 464},
  {'entity_group': 'ORG',
   'score': np.float32(0.9905084),
   'word': 'New York Times Visual Investigations',
   'start': 534,
   'end': 570},
  {'entity_group': 'LOC',
   'score': np.float32(0.5106032),
   'word': 'Donbas',
   'start': 758,
   'end': 764}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.7827247),
   'word': 'Ivankiv Historical and Local History Museum',
   'start': 21,
   'end': 64},
  {'entity_group': 'MISC',
   'score': np.float32(0.9996946),
   'word': 'Russian',
   'start': 131,
   'end': 138},
  {'entity_group': 'PER',
   'score': np.float32(0.97339594),
   'word': 'Maria Prymachenko',
   'start': 210,
   'end': 227},
  {'entity_group': 'PER',
   'score': np.float32(0.9965192),
   'word': 'Hanna Veres',
   'start': 249,
   'end': 260},
  {'entity_group': 'PER',
   'score': np.float32(0.5904014),
   'word': 'Prymachenko',
   'start': 367,
   'end': 378},
  {'entity_group': 'PER',
   'score': np.float32(0.71404696),
   'word': 'Veres',
   'start': 380,
   'end': 385}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.696597),
   'word': 'Babyn Yar Holocaust Memorial Center',
   'start': 4,
   'end': 39},
  {'entity_group': 'LOC',
   'score': np.float32(0.61555237),
   'word': 'Kyiv',
   'start': 298,
   'end': 302},
  {'entity_group': 'ORG',
   'score': np.float32(0.7245123),
   'word': 'Small Opera',
   'start': 303,
   'end': 314}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.82140315),
   'word': 'Dormition Cathedral',
   'start': 4,
   'end': 23},
  {'entity_group': 'LOC',
   'score': np.float32(0.67276376),
   'word': 'Kharkiv',
   'start': 27,
   'end': 34},
  {'entity_group': 'LOC',
   'score': np.float32(0.74528253),
   'word': 'Kharkiv',
   'start': 68,
   'end': 75},
  {'entity_group': 'LOC',
   'score': np.float32(0.7132406),
   'word': 'Kharkiv',
   'start': 175,
   'end': 182},
  {'entity_group': 'ORG',
   'score': np.float32(0.6171724),
   'word': 'Slovo',
   'start': 200,
   'end': 205},
  {'entity_group': 'LOC',
   'score': np.float32(0.7172441),
   'word': 'Building',
   'start': 206,
   'end': 214},
  {'entity_group': 'LOC',
   'score': np.float32(0.74592346),
   'word': 'Kharkiv',
   'start': 218,
   'end': 225},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997763),
   'word': 'Russian',
   'start': 247,
   'end': 254},
  {'entity_group': 'LOC',
   'score': np.float32(0.7487267),
   'word': 'Drobytsky Yar',
   'start': 298,
   'end': 311},
  {'entity_group': 'LOC',
   'score': np.float32(0.74522275),
   'word': 'Kharkiv',
   'start': 332,
   'end': 339},
  {'entity_group': 'MISC',
   'score': np.float32(0.99735045),
   'word': 'Holocaust',
   'start': 353,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.8684192),
   'word': 'Kharkiv Art Museum',
   'start': 404,
   'end': 422},
  {'entity_group': 'LOC',
   'score': np.float32(0.541859),
   'word': 'Kharkiv',
   'start': 605,
   'end': 612},
  {'entity_group': 'ORG',
   'score': np.float32(0.8967781),
   'word': 'Regional Administration',
   'start': 613,
   'end': 636},
  {'entity_group': 'ORG',
   'score': np.float32(0.84705067),
   'word': 'Kharkiv City Council',
   'start': 647,
   'end': 667},
  {'entity_group': 'ORG',
   'score': np.float32(0.9214671),
   'word': 'Opera & Ballet Theatre',
   'start': 673,
   'end': 695},
  {'entity_group': 'ORG',
   'score': np.float32(0.9521331),
   'word': 'Faculty of Economics',
   'start': 704,
   'end': 724},
  {'entity_group': 'ORG',
   'score': np.float32(0.81772065),
   'word': 'Kharkiv University',
   'start': 737,
   'end': 755}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.69855833),
   'word': 'Kharkiv',
   'start': 33,
   'end': 40},
  {'entity_group': 'LOC',
   'score': np.float32(0.5420858),
   'word': 'Izium',
   'start': 52,
   'end': 57},
  {'entity_group': 'MISC',
   'score': np.float32(0.6626214),
   'word': 'Polovtsian',
   'start': 119,
   'end': 129}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997657),

In [ ]:
df_BERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_BERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,LOC,0.998908,Russia,0,6
1,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,LOC,0.998657,Ukraine,40,47
2,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,MISC,0.996759,Russo,98,103
3,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,MISC,0.995493,-,103,104
4,Ukrainian cultural heritage during the 2022 Ru...,0,Russia began the full-scale invasion of Ukrain...,MISC,0.933220,Ukrainian War,104,117
...,...,...,...,...,...,...,...,...
394,Ukrainian cultural heritage during the 2022 Ru...,50,"Egan, Lauren (2022-05-30). ""Ukrainians see the...",LOC,0.996311,Russia,73,79
395,Ukrainian cultural heritage during the 2022 Ru...,50,"Egan, Lauren (2022-05-30). ""Ukrainians see the...",ORG,0.859922,NBC News.,101,110
396,Ukrainian cultural heritage during the 2022 Ru...,51,"""Map of cultural losses"". Ukrainian Cultural F...",ORG,0.992799,Ukrainian Cultural Foundation,26,55
397,Ukrainian cultural heritage during the 2022 Ru...,52,List of damaged objects by Ukrainian Ministry ...,MISC,0.698304,Ukrainian,27,36
398,Ukrainian cultural heritage during the 2022 Ru...,52,List of damaged objects by Ukrainian Ministry ...,ORG,0.975995,Ministry of Culture,37,56

### Model testing and evaluation (done on 10% of the data)

#### subset creation

In [ ]:
all_pages = list(data_processed.keys())

if not all_pages:
    raise ValueError("data_processed contains no pages.")

sample_size = max(1, math.ceil(len(all_pages) * 0.10))

evaluation_pages = (
    pd.Series(all_pages)
    .sample(n=sample_size)
    .tolist()
)

evaluation_data = {
    page: data_processed[page]
    for page in evaluation_pages
}

print(f"Sampled {sample_size} of {len(all_pages)} pages.")

#### DistilBERT

In [ ]:

rows = []

for page, paragraphs in evaluation_data.items():
    for paragraph_id, paragraph in enumerate(paragraphs):
        entities = ner_DistilBERT(paragraph)

        for entity in entities:
            rows.append({
                "entity_group": entity["entity_group"],
                "score": entity["score"],
                "word": entity["word"],
                "start": entity["start"],
                "end": entity["end"],
                "Source": page,
                "Index": paragraph_id,
                "Text": paragraph
            })

columns = [
    "entity_group",
    "score",
    "word",
    "start",
    "end",
    "Source",
    "Index",
    "Text"
]

df_DistilBERT_10pct = pd.DataFrame(rows, columns=columns)

output_dir = os.path.join(
    "NER_output",
    "model_testing_and_evaluation"
)
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(
    output_dir,
    "post_NER_DistilBERT_10pct.csv"
)

df_DistilBERT_10pct.to_csv(output_path, index=False)

print(f"Processed {len(evaluation_data)} sampled pages.")
print(f"Saved {len(df_DistilBERT_10pct)} entity rows to: {output_path}")

df_DistilBERT_10pct.head()

#### BERT

In [ ]:
rows = []

for page, paragraphs in evaluation_data.items():
    for paragraph_id, paragraph in enumerate(paragraphs):
        entities = ner_BERT(paragraph)

        for entity in entities:
            rows.append({
                "entity_group": entity["entity_group"],
                "score": entity["score"],
                "word": entity["word"],
                "start": entity["start"],
                "end": entity["end"],
                "Source": page,
                "Index": paragraph_id,
                "Text": paragraph
            })

columns = [
    "entity_group",
    "score",
    "word",
    "start",
    "end",
    "Source",
    "Index",
    "Text"
]

df_BERT_10pct = pd.DataFrame(rows, columns=columns)

output_dir = os.path.join(
    "NER_output",
    "model_testing_and_evaluation"
)
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(
    output_dir,
    "post_NER_DistilBERT_10pct.csv"
)

df_BERT_10pct.to_csv(output_path, index=False)

print(f"Processed {len(evaluation_data)} sampled pages.")
print(f"Saved {len(df_DistilBERT_10pct)} entity rows to: {output_path}")

df_BERT_10pct.head()

### Full Data

on chosen model (currently DistilBert pending models evaluations)
date: 05.10.26

In [ ]:
rows = []

for page, paragraphs in data_processed.items():
    for paragraph_id, paragraph in enumerate(paragraphs):
        entities = ner_DistilBERT(paragraph)

        for entity in entities:
            rows.append({
                "entity_group": entity["entity_group"],
                "score": entity["score"],
                "word": entity["word"],
                "start": entity["start"],
                "end": entity["end"],
                "Source": page,
                "Index": paragraph_id,
                "Text": paragraph
            })

columns = [
    "entity_group",
    "score",
    "word",
    "start",
    "end",
    "Source",
    "Index",
    "Text"
]

df_DistilBERT = pd.DataFrame(rows, columns=columns)

output_dir = "NER_output"
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(output_dir, "post_NER.csv")
df_DistilBERT.to_csv(output_path, index=False)

print(f"Processed {len(data_processed)} pages.")
print(f"Saved {len(df_DistilBERT)} entity rows to {output_path}")

## Commit to repo

In [ ]:
REPO_PATH = "/content/Corpus2GeoRAG"
GITHUB_USER = "idoschw3"
GITHUB_REPO = "Corpus2GeoRAG"
GITHUB_EMAIL = "193781032+idoschw3@users.noreply.github.com"
COMMIT_MESSAGE = "Update NER workflow"

os.chdir(REPO_PATH)

def run_git(args, *, env=None, capture_output=False):
    """Run Git and raise an error that includes Git's actual output."""
    result = subprocess.run(
        ["git", *args],
        env=env,
        text=True,
        capture_output=capture_output
    )

    if capture_output:
        if result.stdout:
            print(result.stdout, end="")
        if result.stderr:
            print(result.stderr, end="")

    if result.returncode != 0:
        if capture_output:
            details = (result.stderr or result.stdout or "").strip()
        else:
            details = f"Git exited with status {result.returncode}."
        raise RuntimeError(f"git {' '.join(args)} failed:\n{details}")

    return result


# --------------------------------------------------
# Git configuration
# --------------------------------------------------

run_git(["config", "user.name", GITHUB_USER])
run_git(["config", "user.email", GITHUB_EMAIL])
run_git([
    "remote", "set-url", "origin",
    f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}.git"
])

branch = run_git(
    ["branch", "--show-current"],
    capture_output=True
).stdout.strip()

if not branch:
    raise RuntimeError("Could not determine the current Git branch.")

# --------------------------------------------------
# GitHub authentication
# --------------------------------------------------

github_token = userdata.get("GITHUB_TOKEN")

if not github_token:
    raise ValueError(
        "GITHUB_TOKEN is missing from Colab Secrets. "
        "Add it in the Colab Secrets panel and enable notebook access."
    )

askpass_path = "/tmp/github_askpass.sh"

with open(askpass_path, "w") as f:
    f.write(
        "#!/bin/sh\n"
        'case "$1" in\n'
        '  *Username*) printf "%s\\n" "$GITHUB_USER" ;;\n'
        '  *Password*) printf "%s\\n" "$GITHUB_TOKEN" ;;\n'
        "esac\n"
    )

os.chmod(askpass_path, 0o700)

git_env = os.environ.copy()
git_env["GITHUB_USER"] = GITHUB_USER
git_env["GITHUB_TOKEN"] = github_token
git_env["GIT_ASKPASS"] = askpass_path
git_env["GIT_TERMINAL_PROMPT"] = "0"

try:
    # --------------------------------------------------
    # Prevent accidental nested repository
    # --------------------------------------------------

    # Keep this rule only if /content/Corpus2GeoRAG is an accidental
    # nested folder inside the repository. It does not ignore the repo itself.
    ignore_entry = "/Corpus2GeoRAG/"
    gitignore_path = os.path.join(REPO_PATH, ".gitignore")

    existing_ignore = ""
    if os.path.exists(gitignore_path):
        with open(gitignore_path, "r") as f:
            existing_ignore = f.read()

    if ignore_entry not in existing_ignore.splitlines():
        with open(gitignore_path, "a") as f:
            if existing_ignore and not existing_ignore.endswith("\n"):
                f.write("\n")
            f.write(ignore_entry + "\n")

    # If this nested path was already tracked, stop tracking it.
    nested_repo = run_git(
        ["ls-files", "--stage", "--", "Corpus2GeoRAG"],
        capture_output=True
    ).stdout.strip()

    if nested_repo:
        run_git(["rm", "--cached", "-r", "-f", "--", "Corpus2GeoRAG"])
        print("Removed the nested Corpus2GeoRAG path from Git tracking.")

    # --------------------------------------------------
    # Stage repository changes, except local notebook copies
    # --------------------------------------------------

    run_git(["add", "-A"])

    staged_files = run_git(
        ["diff", "--cached", "--name-only"],
        capture_output=True
    ).stdout.splitlines()

    for notebook in staged_files:
        if notebook.endswith(".ipynb"):
            run_git(["restore", "--staged", "--", notebook])

    # --------------------------------------------------
    # Commit staged changes, if any
    # --------------------------------------------------

    staged_diff = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        text=True
    )

    if staged_diff.returncode == 1:
        run_git(["commit", "-m", COMMIT_MESSAGE])
        print("Repository changes committed.")
    elif staged_diff.returncode == 0:
        print("No new repository changes to commit.")
    else:
        raise RuntimeError("Could not check the staged changes.")

    # --------------------------------------------------
    # Restore tracked notebooks to the committed versions
    # --------------------------------------------------

    tracked_files = run_git(
        ["ls-tree", "-r", "--name-only", "HEAD"],
        capture_output=True
    ).stdout.splitlines()

    for notebook in tracked_files:
        if notebook.endswith(".ipynb"):
            run_git(["restore", "--worktree", "--", notebook])

    # --------------------------------------------------
    # Pull/rebase GitHub changes
    # --------------------------------------------------

    pull = subprocess.run(
        ["git", "pull", "--rebase", "origin", branch],
        env=git_env,
        text=True,
        capture_output=True
    )

    if pull.stdout:
        print(pull.stdout, end="")
    if pull.stderr:
        print(pull.stderr, end="")

    if pull.returncode != 0:
        # The known conflict from the earlier run: both sides added
        # .gitignore, and both contained the same single rule.
        conflicted = run_git(
            ["diff", "--name-only", "--diff-filter=U"],
            capture_output=True
        ).stdout.splitlines()

        if conflicted == [".gitignore"]:
            ours = run_git(
                ["show", ":2:.gitignore"],
                capture_output=True
            ).stdout
            theirs = run_git(
                ["show", ":3:.gitignore"],
                capture_output=True
            ).stdout

            if ours.strip() == theirs.strip():
                with open(".gitignore", "w") as f:
                    f.write(ours)
                    if ours and not ours.endswith("\n"):
                        f.write("\n")

                run_git(["add", "--", ".gitignore"])
                run_git(
                    ["-c", "core.editor=true", "rebase", "--continue"]
                )
            else:
                raise RuntimeError(
                    "The pull stopped on a .gitignore conflict, and the two "
                    "versions differ. The rebase is paused; inspect the "
                    "conflict before continuing."
                )
        else:
            raise RuntimeError(
                "The pull failed. The rebase may be paused on a conflict. "
                "Check `git status` before running this cell again."
            )

    # --------------------------------------------------
    # Push the synchronized branch
    # --------------------------------------------------

    run_git(["push", "origin", branch], env=git_env)
    print(f"Successfully pushed to {GITHUB_USER}/{GITHUB_REPO} on branch '{branch}'.")

finally:
    if os.path.exists(askpass_path):
        os.remove(askpass_path)

main
No new repository changes to commit.
.gitignore
ApplyNER/NER.ipynb
ApplyNER/data_initial_cleaning.json
Graph_n_Geocoding/Graph_and_Geocoding.ipynb
LICENSE
README.md
examples/DATA.json
examples/entities_table.csv
Already up to date.
From https://github.com/idoschw3/Corpus2GeoRAG
 * branch            main       -> FETCH_HEAD
Successfully pushed to idoschw3/Corpus2GeoRAG on branch 'main'.