<a href="https://colab.research.google.com/github/idoschw3/Corpus2GeoRAG/blob/main/ApplyNER/NER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
from transformers import pipeline
from tqdm.auto import tqdm
from pathlib import Path
import pandas as pd
import numpy as np
import subprocess
import tempfile
import shutil
import torch
import math
import json
import time
import csv
import os
import io


if os.name == "nt":
    userdata = None
else:
    from google.colab import userdata

### Clone Corpus2GeoRAG Repository

In [23]:
IS_LOCAL = os.name == "nt"

LOCAL_REPO_PATH = Path.home() / "Corpus2GeoRAG"
repo_dir = (
    LOCAL_REPO_PATH
    if IS_LOCAL
    else Path("/content/Corpus2GeoRAG")
)

REPO_PATH = str(repo_dir)

if not repo_dir.exists():
    subprocess.run(
        [
            "git", "clone",
            "https://github.com/EtzionR/Corpus2GeoRAG.git",
            REPO_PATH
        ],
        check=True
    )
elif not (repo_dir / ".git").exists():
    raise RuntimeError(f"{REPO_PATH} exists but is not a Git checkout.")

os.chdir(REPO_PATH)

print("Runtime:", "Local Windows" if IS_LOCAL else "Colab VM")
print("Working folder:", REPO_PATH)

Runtime: Local Windows
Working folder: C:\Users\idosc\Corpus2GeoRAG

### Data Loading and Initial Inspection

**Purpose:** To load the raw text data, which is crucial for subsequent NER tasks, from a JSON file. This section also includes an example to visually inspect the structure and content of a single entry, ensuring the data is correctly loaded and accessible.


**Input/Output:** Input is `/content/Corpus2GeoRAG/examples/DATA.json`.

**Date:** 2026-09-23

In [24]:
PATH = Path(REPO_PATH) / "examples" / "DATA.json"
PATH

WindowsPath('C:/Users/idosc/Corpus2GeoRAG/examples/DATA.json')

In [25]:
with open(PATH, "r", encoding="utf-8") as file:
    data = json.load(file)

len(data)

897

In [26]:
[*data.keys()][:10]

['12 (song)',
 '14 May 2026 Russian strikes on Ukraine',
 '15th BRICS summit',
 '16 March 2022 Chernihiv breadline attack',
 '17 November 2024 Russian strikes on Ukraine',
 '18 March 2022 Mykolaiv military quarters attack',
 '1st European Political Community Summit',
 '2000 Meters to Andriivka',
 '2014 pro-Russian unrest in Ukraine',
 '2020s European re-armament']

In [27]:
example = np.random.choice([*data],1)[0]


print(f'PAGE: {example}:\n\n{data[example]}')

PAGE: Torture of Russian soldiers in Mala Rohan:

The torture of Russian soldiers in Mala Rohan was an incident during the 2022 Russian invasion of Ukraine that occurred in the village of Mala Rohan. As documented by the UN High Commissioner for Human Rights, members of the Ukrainian Armed Forces shot three captured Russian soldiers in the legs and tortured Russian soldiers who were wounded. The incident is reported to have occurred on the evening of March 25, 2022 and was first reported following the publication on social media of a video of unknown authorship between March 27 and March 28. As a case of summary execution and torture of prisoners of war, the incident might qualify as a war crime.


== Video ==
On the morning of March 27, two videos were posted on Reddit and Twitter, and a more complete version, two minutes longer, later appeared on YouTube. The Times reported that the videos had been promoted by Maria Dubovikova of the Russian International Affairs Council, but their original source is unclear. According to BBC News and CheckNews (the fact-checking service of Libération), videos released by fighters of the Azov Regiment-affiliated Kraken Regiment who were active in the area show several dozen Russian prisoners, some in their underwear, lined up in front of a ditch and then piled into vehicles; another video shows blindfolded Russian prisoners singing the Ukrainian anthem.
The video shows five people in military uniforms; some with white bands on their arms, which are worn by Russian forces. They are lying on the ground with their hands tied. Two of them have white bags over their heads and at least three appear to be wounded in the leg. The prisoners are questioned by their captors, who speak Russian with Ukrainian accents and wear yellow and blue markings used by the Ukrainian forces. The prisoners are accused of having bombed Kharkiv. During interrogation some of the prisoners appear to be losing consciousness.
Two more people are driven into the courtyard in a van and promptly shot in their legs, along with another man standing nearby. One of the new arrivals is hit in the head with the butt of a rifle. The interrogation of prisoners by a man is heard behind the camera, as well as a conversation in Russian without a foreign accent, presumably on a walkie-talkie.
Based on weather conditions and the position of the sun, the BBC suggested that the video could have been shot early in the day on March 26. France 24 suggested that the video could have been filmed between March 11 and 27, again based on weather conditions. Open data researcher Erich Auerbach reported that the footage took place on a farm in the village of Mala Rohan, 18 km (11 mi) east of the center of Kharkiv. This geolocation was confirmed by Human Rights Watch and The Washington Post. According to Ukrainian statements, this village was retaken by the Ukrainian Armed Forces two days before the first videos appeared.
The perpetrators in the video wore blue armbands, which Human Rights Watch noted are usually worn by Ukrainian forces, while all except one of the POWs (who donned a red one) had white armbands, both colours in use by Russian forces. According to Human Rights Watch, the affiliation of the perpetrators is unclear: they are dressed in various uniforms, hold various weapons, and have various equipment without obvious insignia. Nick Reynolds, a military expert at the Royal United Institute of Defense Studies, said an assault rifle in the video resembled camouflaged weapons used by the Ukrainian Special Operations Forces but is slightly different from any he had previously seen; he also noted that both parties in the conflict used weapons captured from the other side.
On May 13, investigative reporters at the French outlet Le Monde published a video in which they geolocated the original footage, confirming the findings reported by Erich Auerbach. According to Le Monde, an analysis of the weather conditions and videos shot in the area shows that the video with the Russian prisoners of war was filmed on the evening of March 25. In videos shot during the battle for Mala Rohan, members of the Ukrainian Slobozhanshchyna battalion are present, and their leader, Andriy Yanholenko, clearly appears in the same frame as the prisoners who were later shot in the knees. In that frame he appears to be gathering the three Russian prisoners in a location 700 meters away from the farm where they will be shot.
On 29 June, the United Nations High Commissioner for Human Rights published a report in which the incident in Mala Rohan is mentioned as one of two "documented cases of summary execution and torture of Russian prisoners of war and persons hors de combat reportedly perpetrated by members of Ukrainian armed forces." As reported by the human rights agency, members of Ukrainian armed forces shot three captured Russian soldiers in the legs and tortured Russian soldiers who were wounded. The report also mentions that one of the participants of the event later acknowledged that some of his comrades did torture Russian soldiers.
A Russian woman has claimed that one of the Russian POWs shown in the video is her adopted son Ivan Kudryavtsev, a 20-year-old conscripted soldier from Omsk Oblast. He is identified as a wounded soldier who loses consciousness while being interrogated. On April 29, the Russian Defense Ministry confirmed that he went missing during military service.


== Reactions ==


=== From Ukrainian authorities ===
On 27 March Valerii Zaluzhnyi, commander-in-chief of the Armed Forces of Ukraine, called the video staged and accused Russia of creating it to discredit the Ukrainian forces. Ukraine's ombudsman for human rights at the time, Lyudmyla Denisova, dismissed the footage as fake.
Later that day, Oleksii Arestovych, adviser to the head of the office of the President of Ukraine, said that the unlawful treatment of prisoners qualifies as a war crime and should be punished. He also stated that an investigation will be conducted, and the inadmissibility of such actions would be reiterated to defense forces personnel.
Iryna Venediktova, the Prosecutor General of Ukraine at the time, said that investigations and prosecutions would be carried out if the evidence were strong enough.


== See also ==
Makiivka surrender incident
Torture and castration of a Ukrainian POW in Pryvillia
War crimes in the 2022 Russian invasion of Ukraine § Mistreatment of prisoners of war
Execution of Oleksandr Matsievskyi
Beheading of a Ukrainian prisoner of war in summer 2022


== References ==

In [28]:
TITLE = '=='
MIN_LENGTH = 5

paragraphs = data[example].split('\n')
paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]

print(f'{len(paragraphs_processed)} Paragraphs Extracted from {len(paragraphs)}\n{round(len(paragraphs_processed)/len(paragraphs)*100,1)}%')

17 Paragraphs Extracted from 32
53.1%

### Text Preprocessing: Paragraph Filtering

**Purpose:** To perform an initial cleaning of the raw text by filtering out structural elements and short, uninformative lines. This step aims to prepare cleaner text segments for downstream NER processing by removing elements such as section titles and empty or minimal lines.

**Date:** 2026-09-24

In [29]:
TITLE = '=='
MIN_LENGTH = 5

data_processed = {}

total_paragraphs = 0
total_processed = 0

for key, text in data.items():
  paragraphs = text.split('\n')
  paragraphs_processed = [text for text in paragraphs if text.startswith(TITLE)==False and len(text)>=MIN_LENGTH]
  data_processed[key] = paragraphs_processed

  total_paragraphs += len(paragraphs)
  total_processed += len(paragraphs_processed)

print(f'{total_processed} paragraphs extracted from {total_paragraphs}\n {round(total_processed/total_paragraphs*100,1)}%')

42822 paragraphs extracted from 88029
 48.6%

In [30]:
example = np.random.choice([*data_processed],1)[0]

print(f'PAGE: {example}:\n\n{data_processed[example]}')

PAGE: Zapad 2021:

['Zapad 2021 (Russian: Запад-2021, English: West 2021) was a joint strategic exercise between the armed forces of the Russian Federation and Belarus, which took place from 10 to 15 September 2021. According to the Ministry of Defence of the Russian Federation, approximately 200,000 military personnel, up to 760 pieces of equipment, and 15 ships participated in the exercises.', 'According to some international experts, the exercise was part of Russian preparation for the subsequent invasion of Ukraine.', 'Strategic exercises between Belarus and Russia are held every two years, as per an agreement reached between Russian President Dmitry Medvedev and Belarusian President Alexander Lukashenko in 2009. In 2021, they were combined with maneuvers of the Collective Rapid Reaction Forces of the CSTO member states.', 'According to First Deputy Minister of Defense of the Republic of Belarus, Major General Viktor Gulevich, "Zapad-2021 is purely defensive, and its holding does not pose any threat, either to the European community as a whole or to neighboring countries in particular. Zapad-2021 is planned and is the final stage in the system of joint training of the armed forces of Belarus and Russia this year. Its primary objective is to enhance the preparedness of troops from the regional grouping tasked with ensuring security in the Eastern European region."', "On September 1, the stage planned by the General Staff to enhance the country's defense capability was completed: a reserve army of 38,000 combat troops was established in the Southern Military District.", 'Exercises were conducted on Belarusian territory at the 230th combined arms training ground "Obuz-Lesnovsky", the 174th training ground of the Air Force and Air Defense forces "Domanovsky", the 210th aviation training ground "Ruzhansky", and the Brest training ground, as well as 9 Russian training grounds (Kirillovsky, Strugi Krasnye, Mulino, Pogonovo, Khmelevka, Pravdinsky, Dobrovolsky, Dorogobuzh, Volsky).', 'Up to 760 armored vehicles, including around 290 tanks, 240 artillery, and MLRS units, as well as over 80 aircraft and helicopters, participated in the exercises.', 'For the first time, a fully robotic group of combined arms units participated in the exercises in combat formations, which included robots such as "Uran-9", "Nerekhta", and others. They were supported by a laser system designed to blind the sights of tanks, artillery systems, and sniper rifles.', 'Additionally, 400 Belarusian servicemen and over 30 pieces of military equipment went to Russia. The Ministry of Defense of the Republic of Belarus announced that all troops and equipment would return to their permanent locations after the exercises.', 'The exercises commenced on 10 September, involving 200,000 military personnel, 760 units of military equipment (including over 80 aircraft and helicopters, more than 290 tanks, 240 guns, multiple rocket launchers, and mortars), and 15 ships. They commenced simultaneously at 14 military ranges: Kirilovsky, Strugi Krasnye, Mulino, Pogonovo, Khmelevka, Pravdinsky, Dobrovolsky, Dorogobuzh, and Volsky, located on the territory of the Russian Federation, in the Baltic Sea, as well as at five ranges in the Republic of Belarus — Obuz-Lesnovsky, Brest, Chepelevo, Domanovsky, and Ruzhansky. The opening of the exercises took place in Mulino near Nizhny Novgorod.', "The tactical concept of the Zapad-2021 exercises was standard: repelling the enemy's attack, drawing the enemy in, encircling, destroying, and going on the offensive.", 'The defending units were supported by 12 divisions (140 guns) of modernized self-propelled howitzers "Msta-S" (providing the so-called "Fire Shaft").', 'At the training grounds in the Kaliningrad Oblast, the military practiced actions to eliminate conditional illegal armed formations in urban conditions, as well as strikes against stationary and mobile targets. For the first time, the Platform-M ground-based robotic complexes were used there - robots armed with grenade launchers and a Kalashnikov assault rifle were successfully utilized by motorized infantry and paratroopers who controlled the process remotely.', 'T-72B3 tanks, equipped with additional dynamic protection and anti-mine trawls, along with the Terminator BMPT, played a significant role in the ground force offensive. A platoon of the latest B-19 infantry fighting vehicles, fitted with the Epoch combat module, entered combat. Additionally, the heavy flamethrower systems TOS-1A "Solntsepek" collaborated for the first time with the latest remote mining complexes "Agriculture."', 'For the first time, engineering, surveillance, and strike robots played a significant role in the combat training of troops, alongside tanks and other ground and aviation equipment. The most notable were the Uran family machines, which directly engaged in battle formations with defending units and provided cover for the forces during position changes by motorized rifle units. Additionally, the Nerekhta robots were utilized for reconnaissance and fire support.', 'For the first time, reconnaissance and strike UAVs were extensively deployed for operational purposes, providing cover for the maneuvering actions of defending units. They operated alongside the Sagittarius intelligence and communications complex.', 'Simultaneously, various groups of army aviation were engaged: Su-35S, Su-30SM, MiG-31BM, and Su-34 fighters provided air cover for the troop grouping. Helicopters, including variously modified Mi-8s, reconnaissance and strike Mi-28 "Night Hunter," attack Ka-52 "Alligator," and Mi-35s, operated at the forefront of the counteroffensive. They conducted tactical troop landings and transported equipment and weapons externally. Additionally, four squadrons of Su-34S fighter-bombers targeted key enemy defense installations.', 'The official "closing" ceremony took place on 15 September at the Mulino training ground in Nizhny Novgorod.', 'International media and observers concluded that the activity represented training in preparation for a conflict with other European, probably NATO-aligned countries; the "fictional" enemies of the Russian and Belarusian units included forces from "Neris (a Lithuanian river), Pomoria and Polar Republic", which according to the exercise fomented domestic unrest in Belarus and then proceeded to invade it, leading to a Belarusian-Russian counterattack.', 'According to American General and Chairman of the Joint Chiefs of Staff Mark Milley, observations of Zapad 2021 helped the American intelligence community predict that the Russian invasion of Ukraine was imminent. This was because the exercise was much greater in scale, scope, composition, and duration than previous exercises. Following the exercise, Milley held a briefing with American President Joe Biden about the severity of the Russian threat towards Ukraine. Milley held a meeting with Chief of General Staff of the Russian Armed Forces, Valery Gerasimov, in Finland, on September 22, 2021, to de-escalate tensions in Europe.', 'Warsaw-based Belarusian former politician and dissident Andrej Sannikau also argued that Zapad 2021 was a preparation for the invasion.', 'List of Zapad exercises']

In [31]:
SAVE_PATH = Path(REPO_PATH) / "ApplyNER" / "data_initial_cleaning.json"
SAVE_PATH.parent.mkdir(parents=True, exist_ok=True)

with open(SAVE_PATH, "w", encoding="utf-8") as f:
    json.dump(data_processed, f, ensure_ascii=False, indent=2)

print(f"Saved to: {SAVE_PATH}")

Saved to: C:\Users\idosc\Corpus2GeoRAG\ApplyNER\data_initial_cleaning.json

## Initial NER application

**Purpose:** To perform an initial NER application with base models and analyze the results

**Date:** 2026-09-24

### example

#### DistilBERT

In [32]:
MODEL_DistilBERT = "dslim/distilbert-NER"

ner_DistilBERT = pipeline(
    "ner",
    model=MODEL_DistilBERT,
    aggregation_strategy="average",
    device=0 if torch.cuda.is_available() else -1
)

print("Model device:", ner_DistilBERT.device)

ner_DistilBERT

Loading weights: 100%|██████████| 102/102 [00:00<00:00, 473.83it/s]

Model device: cuda:0

TokenClassificationPipeline: {'model': 'DistilBertForTokenClassification', 'dtype': 'float32', 'device': 'cuda', 'input_modalities': 'text'}

In [33]:
output_DistilBERT = ner_DistilBERT(data_processed[example])
output_DistilBERT

[[{'entity_group': 'MISC',
   'score': np.float32(0.53940827),
   'word': 'Zapad',
   'start': 0,
   'end': 5},
  {'entity_group': 'MISC',
   'score': np.float32(0.839036),
   'word': 'Russian',
   'start': 12,
   'end': 19},
  {'entity_group': 'MISC',
   'score': np.float32(0.7054061),
   'word': 'English',
   'start': 33,
   'end': 40},
  {'entity_group': 'LOC',
   'score': np.float32(0.74097437),
   'word': 'West',
   'start': 42,
   'end': 46},
  {'entity_group': 'LOC',
   'score': np.float32(0.9661194),
   'word': 'Russian Federation',
   'start': 116,
   'end': 134},
  {'entity_group': 'LOC',
   'score': np.float32(0.99835545),
   'word': 'Belarus',
   'start': 139,
   'end': 146},
  {'entity_group': 'ORG',
   'score': np.float32(0.97504026),
   'word': 'Ministry of Defence',
   'start': 212,
   'end': 231},
  {'entity_group': 'LOC',
   'score': np.float32(0.9573382),
   'word': 'Russian Federation',
   'start': 239,
   'end': 257}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99760985),
   'word': 'Russian',
   'start': 66,
   'end': 73},
  {'entity_group': 'LOC',
   'score': np.float32(0.9978607),
   'word': 'Ukraine',
   'start': 117,
   'end': 124}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.99870074),
   'word': 'Belarus',
   'start': 28,
   'end': 35},
  {'entity_group': 'LOC',
   'score': np.float32(0.9988341),
   'word': 'Russia',
   'start': 40,
   'end': 46},
  {'entity_group': 'MISC',
   'score': np.float32(0.99730057),
   'word': 'Russian',
   'start': 109,
   'end': 116},
  {'entity_group': 'PER',
   'score': np.float32(0.99764585),
   'word': 'Dmitry Medvedev',
   'start': 127,
   'end': 142},
  {'entity_group': 'MISC',
   'score': np.float32(0.99627054),
   'word': 'Belarusian',
   'start': 147,
   'end': 157},
  {'entity_group': 'PER',
   'score': np.float32(0.9987445),
   'word': 'Alexander Lukashenko',
   'start': 168,
   'end': 188},
  {'entity_group': 'ORG',
   'score': np.float32(0.8847767),
   'word': 'Collective Rapid Reaction Forces',
   'start': 248,
   'end': 280},
  {'entity_group': 'ORG',
   'score': np.float32(0.9975842),
   'word': 'CSTO',
   'start': 288,
   'end': 292}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.82131594),
   'word': 'Republic',
   'start': 53,
   'end': 61},
  {'entity_group': 'ORG',
   'score': np.float32(0.4874431),
   'word': 'of',
   'start': 62,
   'end': 64},
  {'entity_group': 'LOC',
   'score': np.float32(0.7629478),
   'word': 'Belarus',
   'start': 65,
   'end': 72},
  {'entity_group': 'PER',
   'score': np.float32(0.9981999),
   'word': 'Viktor Gulevich',
   'start': 88,
   'end': 103},
  {'entity_group': 'MISC',
   'score': np.float32(0.86012393),
   'word': 'Zapad',
   'start': 106,
   'end': 111},
  {'entity_group': 'MISC',
   'score': np.float32(0.56203604),
   'word': '-',
   'start': 111,
   'end': 112},
  {'entity_group': 'MISC',
   'score': np.float32(0.99598026),
   'word': 'European',
   'start': 194,
   'end': 202},
  {'entity_group': 'MISC',
   'score': np.float32(0.8490754),
   'word': 'Zapad',
   'start': 267,
   'end': 272},
  {'entity_group': 'LOC',
   'score': np.float32(0.998901),
   'word': 'Belarus',
   'start': 367,
   'end': 374},
  {'entity_group': 'LOC',
   'score': np.float32(0.99869746),
   'word': 'Russia',
   'start': 379,
   'end': 385},
  {'entity_group': 'MISC',
   'score': np.float32(0.90155697),
   'word': 'Eastern European',
   'start': 524,
   'end': 540}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.78848064),
   'word': 'General Staff',
   'start': 41,
   'end': 54},
  {'entity_group': 'LOC',
   'score': np.float32(0.9383989),
   'word': 'Southern Military District',
   'start': 176,
   'end': 202}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9930782),
   'word': 'Belarusian',
   'start': 28,
   'end': 38},
  {'entity_group': 'LOC',
   'score': np.float32(0.9927628),
   'word': 'Obuz',
   'start': 93,
   'end': 97},
  {'entity_group': 'LOC',
   'score': np.float32(0.991653),
   'word': '-',
   'start': 97,
   'end': 98},
  {'entity_group': 'LOC',
   'score': np.float32(0.71330947),
   'word': 'Lesnovsky',
   'start': 98,
   'end': 107},
  {'entity_group': 'ORG',
   'score': np.float32(0.98777807),
   'word': 'Air Force',
   'start': 143,
   'end': 152},
  {'entity_group': 'ORG',
   'score': np.float32(0.92266965),
   'word': 'Air Defense',
   'start': 157,
   'end': 168},
  {'entity_group': 'ORG',
   'score': np.float32(0.69374305),
   'word': 'Domanovsky',
   'start': 177,
   'end': 187},
  {'entity_group': 'LOC',
   'score': np.float32(0.98900837),
   'word': 'Ruzhansky',
   'start': 226,
   'end': 235},
  {'entity_group': 'LOC',
   'score': np.float32(0.94171256),
   'word': 'Brest',
   'start': 246,
   'end': 251},
  {'entity_group': 'MISC',
   'score': np.float32(0.99805766),
   'word': 'Russian',
   'start': 282,
   'end': 289},
  {'entity_group': 'LOC',
   'score': np.float32(0.9863014),
   'word': 'Kirillovsky',
   'start': 308,
   'end': 319},
  {'entity_group': 'LOC',
   'score': np.float32(0.93903196),
   'word': 'Strugi Krasnye',
   'start': 321,
   'end': 335},
  {'entity_group': 'LOC',
   'score': np.float32(0.9947161),
   'word': 'Mulino',
   'start': 337,
   'end': 343},
  {'entity_group': 'LOC',
   'score': np.float32(0.99226093),
   'word': 'Pogonovo',
   'start': 345,
   'end': 353},
  {'entity_group': 'LOC',
   'score': np.float32(0.9872031),
   'word': 'Khmelevka',
   'start': 355,
   'end': 364},
  {'entity_group': 'LOC',
   'score': np.float32(0.9953968),
   'word': 'Pravdinsky',
   'start': 366,
   'end': 376},
  {'entity_group': 'LOC',
   'score': np.float32(0.9907238),
   'word': 'Dobrovolsky',
   'start': 378,
   'end': 389},
  {'entity_group': 'LOC',
   'score': np.float32(0.99268514),
   'word': 'Dorogobuzh',
   'start': 391,
   'end': 401},
  {'entity_group': 'LOC',
   'score': np.float32(0.9951328),
   'word': 'Volsky',
   'start': 403,
   'end': 409}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.92446786),
   'word': 'MLRS',
   'start': 75,
   'end': 79}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.6549258),
   'word': 'Uran',
   'start': 148,
   'end': 152},
  {'entity_group': 'ORG',
   'score': np.float32(0.49538162),
   'word': '-',
   'start': 152,
   'end': 153},
  {'entity_group': 'MISC',
   'score': np.float32(0.66683036),
   'word': '9',
   'start': 153,
   'end': 154},
  {'entity_group': 'ORG',
   'score': np.float32(0.8037256),
   'word': 'Nerekhta',
   'start': 158,
   'end': 166}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9964295),
   'word': 'Belarusian',
   'start': 18,
   'end': 28},
  {'entity_group': 'LOC',
   'score': np.float32(0.99876297),
   'word': 'Russia',
   'start': 89,
   'end': 95},
  {'entity_group': 'ORG',
   'score': np.float32(0.87225235),
   'word': 'Ministry of Defense of the Republic of Belarus',
   'start': 101,
   'end': 147}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9929803),
   'word': 'Kirilovsky',
   'start': 295,
   'end': 305},
  {'entity_group': 'LOC',
   'score': np.float32(0.97594965),
   'word': 'Strugi Krasnye',
   'start': 307,
   'end': 321},
  {'entity_group': 'LOC',
   'score': np.float32(0.9961447),
   'word': 'Mulino',
   'start': 323,
   'end': 329},
  {'entity_group': 'LOC',
   'score': np.float32(0.9940041),
   'word': 'Pogonovo',
   'start': 331,
   'end': 339},
  {'entity_group': 'LOC',
   'score': np.float32(0.9908918),
   'word': 'Khmelevka',
   'start': 341,
   'end': 350},
  {'entity_group': 'LOC',
   'score': np.float32(0.9963404),
   'word': 'Pravdinsky',
   'start': 352,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.99335355),
   'word': 'Dobrovolsky',
   'start': 364,
   'end': 375},
  {'entity_group': 'LOC',
   'score': np.float32(0.99483156),
   'word': 'Dorogobuzh',
   'start': 377,
   'end': 387},
  {'entity_group': 'LOC',
   'score': np.float32(0.99598837),
   'word': 'Volsky',
   'start': 393,
   'end': 399},
  {'entity_group': 'LOC',
   'score': np.float32(0.99321127),
   'word': 'Russian Federation',
   'start': 433,
   'end': 451},
  {'entity_group': 'LOC',
   'score': np.float32(0.9949677),
   'word': 'Baltic Sea',
   'start': 460,
   'end': 470},
  {'entity_group': 'LOC',
   'score': np.float32(0.86287355),
   'word': 'Republic of Belarus',
   'start': 505,
   'end': 524},
  {'entity_group': 'LOC',
   'score': np.float32(0.9966125),
   'word': 'Obuz',
   'start': 527,
   'end': 531},
  {'entity_group': 'LOC',
   'score': np.float32(0.99248534),
   'word': '-',
   'start': 531,
   'end': 532},
  {'entity_group': 'LOC',
   'score': np.float32(0.7980589),
   'word': 'Lesnovsky',
   'start': 532,
   'end': 541},
  {'entity_group': 'LOC',
   'score': np.float32(0.9984378),
   'word': 'Brest',
   'start': 543,
   'end': 548},
  {'entity_group': 'LOC',
   'score': np.float32(0.9961929),
   'word': 'Chepelevo',
   'start': 550,
   'end': 559},
  {'entity_group': 'LOC',
   'score': np.float32(0.9972152),
   'word': 'Domanovsky',
   'start': 561,
   'end': 571},
  {'entity_group': 'LOC',
   'score': np.float32(0.99740165),
   'word': 'Ruzhansky',
   'start': 577,
   'end': 586},
  {'entity_group': 'LOC',
   'score': np.float32(0.9968542),
   'word': 'Mulino',
   'start': 631,
   'end': 637},
  {'entity_group': 'LOC',
   'score': np.float32(0.98603314),
   'word': 'Nizhny Novgorod',
   'start': 643,
   'end': 658}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.98682064),
   'word': 'Zapad',
   'start': 28,
   'end': 33},
  {'entity_group': 'MISC',
   'score': np.float32(0.98387086),
   'word': '-',
   'start': 33,
   'end': 34},
  {'entity_group': 'MISC',
   'score': np.float32(0.85287476),
   'word': '2021',
   'start': 34,
   'end': 38}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.6692947),
   'word': 'Msta',
   'start': 102,
   'end': 106},
  {'entity_group': 'MISC',
   'score': np.float32(0.4683128),
   'word': '-',
   'start': 106,
   'end': 107},
  {'entity_group': 'MISC',
   'score': np.float32(0.5506749),
   'word': 'S',
   'start': 107,
   'end': 108}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.929777),
   'word': 'Kaliningrad Oblast',
   'start': 31,
   'end': 49},
  {'entity_group': 'MISC',
   'score': np.float32(0.9565259),
   'word': 'Platform',
   'start': 235,
   'end': 243},
  {'entity_group': 'MISC',
   'score': np.float32(0.94666094),
   'word': '-',
   'start': 243,
   'end': 244},
  {'entity_group': 'MISC',
   'score': np.float32(0.94266427),
   'word': 'M',
   'start': 244,
   'end': 245},
  {'entity_group': 'MISC',
   'score': np.float32(0.9142776),
   'word': 'Kalashnikov',
   'start': 337,
   'end': 348}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.95148915),
   'word': 'T',
   'start': 0,
   'end': 1},
  {'entity_group': 'MISC',
   'score': np.float32(0.9624046),
   'word': '-',
   'start': 1,
   'end': 2},
  {'entity_group': 'MISC',
   'score': np.float32(0.9448943),
   'word': '72B3',
   'start': 2,
   'end': 6},
  {'entity_group': 'MISC',
   'score': np.float32(0.74758583),
   'word': 'Terminator BMPT',
   'start': 95,
   'end': 110},
  {'entity_group': 'MISC',
   'score': np.float32(0.92940927),
   'word': 'B',
   'start': 193,
   'end': 194},
  {'entity_group': 'MISC',
   'score': np.float32(0.9228758),
   'word': '-',
   'start': 194,
   'end': 195},
  {'entity_group': 'MISC',
   'score': np.float32(0.8650743),
   'word': '19',
   'start': 195,
   'end': 197},
  {'entity_group': 'MISC',
   'score': np.float32(0.39882),
   'word': 'Epoch',
   'start': 242,
   'end': 247},
  {'entity_group': 'MISC',
   'score': np.float32(0.8790794),
   'word': 'TOS',
   'start': 324,
   'end': 327},
  {'entity_group': 'MISC',
   'score': np.float32(0.9114371),
   'word': '-',
   'start': 327,
   'end': 328},
  {'entity_group': 'MISC',
   'score': np.float32(0.91565496),
   'word': '1A',
   'start': 328,
   'end': 330},
  {'entity_group': 'ORG',
   'score': np.float32(0.95583725),
   'word': 'Solntsepek',
   'start': 332,
   'end': 342},
  {'entity_group': 'ORG',
   'score': np.float32(0.8035733),
   'word': 'Agriculture',
   'start': 417,
   'end': 428}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9165584),
   'word': 'Uran',
   'start': 208,
   'end': 212},
  {'entity_group': 'ORG',
   'score': np.float32(0.6941071),
   'word': 'Nerekhta',
   'start': 397,
   'end': 405}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9416597),
   'word': 'Sagittarius',
   'start': 195,
   'end': 206}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.6501718),
   'word': 'Su',
   'start': 62,
   'end': 64},
  {'entity_group': 'MISC',
   'score': np.float32(0.7108129),
   'word': '-',
   'start': 64,
   'end': 65},
  {'entity_group': 'MISC',
   'score': np.float32(0.4860449),
   'word': '35S',
   'start': 65,
   'end': 68},
  {'entity_group': 'MISC',
   'score': np.float32(0.61723745),
   'word': 'Su',
   'start': 70,
   'end': 72},
  {'entity_group': 'MISC',
   'score': np.float32(0.671577),
   'word': '-',
   'start': 72,
   'end': 73},
  {'entity_group': 'ORG',
   'score': np.float32(0.44364363),
   'word': '30SM',
   'start': 73,
   'end': 77},
  {'entity_group': 'MISC',
   'score': np.float32(0.75522393),
   'word': 'MiG',
   'start': 79,
   'end': 82},
  {'entity_group': 'MISC',
   'score': np.float32(0.8573264),
   'word': '-',
   'start': 82,
   'end': 83},
  {'entity_group': 'MISC',
   'score': np.float32(0.6927893),
   'word': '31BM',
   'start': 83,
   'end': 87},
  {'entity_group': 'MISC',
   'score': np.float32(0.9216799),
   'word': 'Su',
   'start': 93,
   'end': 95},
  {'entity_group': 'MISC',
   'score': np.float32(0.92361504),
   'word': '-',
   'start': 95,
   'end': 96},
  {'entity_group': 'MISC',
   'score': np.float32(0.9348688),
   'word': '34',
   'start': 96,
   'end': 98},
  {'entity_group': 'MISC',
   'score': np.float32(0.9233692),
   'word': 'Mi',
   'start': 193,
   'end': 195},
  {'entity_group': 'MISC',
   'score': np.float32(0.9296414),
   'word': '-',
   'start': 195,
   'end': 196},
  {'entity_group': 'MISC',
   'score': np.float32(0.888892),
   'word': '8s',
   'start': 196,
   'end': 198},
  {'entity_group': 'MISC',
   'score': np.float32(0.9400356),
   'word': 'Mi',
   'start': 226,
   'end': 228},
  {'entity_group': 'MISC',
   'score': np.float32(0.96274745),
   'word': '-',
   'start': 228,
   'end': 229},
  {'entity_group': 'MISC',
   'score': np.float32(0.90937954),
   'word': '28',
   'start': 229,
   'end': 231},
  {'entity_group': 'MISC',
   'score': np.float32(0.79059434),
   'word': 'Night Hunter',
   'start': 233,
   'end': 245},
  {'entity_group': 'MISC',
   'score': np.float32(0.9768933),
   'word': 'Ka',
   'start': 255,
   'end': 257},
  {'entity_group': 'MISC',
   'score': np.float32(0.9831687),
   'word': '-',
   'start': 257,
   'end': 258},
  {'entity_group': 'MISC',
   'score': np.float32(0.95232683),
   'word': '52',
   'start': 258,
   'end': 260},
  {'entity_group': 'MISC',
   'score': np.float32(0.4869152),
   'word': 'Alligator',
   'start': 262,
   'end': 271},
  {'entity_group': 'MISC',
   'score': np.float32(0.96873003),
   'word': 'Mi',
   'start': 278,
   'end': 280},
  {'entity_group': 'MISC',
   'score': np.float32(0.9698411),
   'word': '-',
   'start': 280,
   'end': 281},
  {'entity_group': 'MISC',
   'score': np.float32(0.93061674),
   'word': '35s',
   'start': 281,
   'end': 284},
  {'entity_group': 'MISC',
   'score': np.float32(0.9042355),
   'word': 'Su',
   'start': 458,
   'end': 460},
  {'entity_group': 'MISC',
   'score': np.float32(0.9138435),
   'word': '-',
   'start': 460,
   'end': 461},
  {'entity_group': 'MISC',
   'score': np.float32(0.8798739),
   'word': '34S',
   'start': 461,
   'end': 464}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9227631),
   'word': 'Mulino',
   'start': 66,
   'end': 72},
  {'entity_group': 'LOC',
   'score': np.float32(0.9923079),
   'word': 'Nizhny Novgorod',
   'start': 92,
   'end': 107}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99860555),
   'word': 'European',
   'start': 124,
   'end': 132},
  {'entity_group': 'MISC',
   'score': np.float32(0.99707377),
   'word': 'NATO',
   'start': 143,
   'end': 147},
  {'entity_group': 'MISC',
   'score': np.float32(0.97574085),
   'word': '-',
   'start': 147,
   'end': 148},
  {'entity_group': 'MISC',
   'score': np.float32(0.9731559),
   'word': 'aligned',
   'start': 148,
   'end': 155},
  {'entity_group': 'MISC',
   'score': np.float32(0.9981622),
   'word': 'Russian',
   'start': 198,
   'end': 205},
  {'entity_group': 'MISC',
   'score': np.float32(0.99463874),
   'word': 'Belarusian',
   'start': 210,
   'end': 220},
  {'entity_group': 'LOC',
   'score': np.float32(0.9888658),
   'word': 'Neris',
   'start': 249,
   'end': 254},
  {'entity_group': 'MISC',
   'score': np.float32(0.95163107),
   'word': 'Lithuanian',
   'start': 258,
   'end': 268},
  {'entity_group': 'LOC',
   'score': np.float32(0.9968376),
   'word': 'Pomoria',
   'start': 277,
   'end': 284},
  {'entity_group': 'LOC',
   'score': np.float32(0.9957409),
   'word': 'Polar Republic',
   'start': 289,
   'end': 303},
  {'entity_group': 'LOC',
   'score': np.float32(0.9978999),
   'word': 'Belarus',
   'start': 366,
   'end': 373},
  {'entity_group': 'MISC',
   'score': np.float32(0.9979304),
   'word': 'Belarusian',
   'start': 420,
   'end': 430},
  {'entity_group': 'MISC',
   'score': np.float32(0.987536),
   'word': '-',
   'start': 430,
   'end': 431},
  {'entity_group': 'MISC',
   'score': np.float32(0.9968959),
   'word': 'Russian',
   'start': 431,
   'end': 438}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99823534),
   'word': 'American',
   'start': 13,
   'end': 21},
  {'entity_group': 'ORG',
   'score': np.float32(0.9115091),
   'word': 'Joint Chiefs of Staff',
   'start': 50,
   'end': 71},
  {'entity_group': 'PER',
   'score': np.float32(0.9942316),
   'word': 'Mark Milley',
   'start': 72,
   'end': 83},
  {'entity_group': 'MISC',
   'score': np.float32(0.5889626),
   'word': 'Zapad',
   'start': 101,
   'end': 106},
  {'entity_group': 'MISC',
   'score': np.float32(0.998672),
   'word': 'American',
   'start': 123,
   'end': 131},
  {'entity_group': 'MISC',
   'score': np.float32(0.9987148),
   'word': 'Russian',
   'start': 172,
   'end': 179},
  {'entity_group': 'LOC',
   'score': np.float32(0.99823856),
   'word': 'Ukraine',
   'start': 192,
   'end': 199},
  {'entity_group': 'PER',
   'score': np.float32(0.99622416),
   'word': 'Milley',
   'start': 353,
   'end': 359},
  {'entity_group': 'MISC',
   'score': np.float32(0.99679786),
   'word': 'American',
   'start': 381,
   'end': 389},
  {'entity_group': 'PER',
   'score': np.float32(0.9986832),
   'word': 'Joe Biden',
   'start': 400,
   'end': 409},
  {'entity_group': 'MISC',
   'score': np.float32(0.9988356),
   'word': 'Russian',
   'start': 436,
   'end': 443},
  {'entity_group': 'LOC',
   'score': np.float32(0.99876297),
   'word': 'Ukraine',
   'start': 459,
   'end': 466},
  {'entity_group': 'PER',
   'score': np.float32(0.9904974),
   'word': 'Milley',
   'start': 468,
   'end': 474},
  {'entity_group': 'ORG',
   'score': np.float32(0.98480606),
   'word': 'Russian Armed Forces',
   'start': 525,
   'end': 545},
  {'entity_group': 'PER',
   'score': np.float32(0.99807703),
   'word': 'Valery Gerasimov',
   'start': 547,
   'end': 563},
  {'entity_group': 'LOC',
   'score': np.float32(0.99903995),
   'word': 'Finland',
   'start': 568,
   'end': 575},
  {'entity_group': 'LOC',
   'score': np.float32(0.99881256),
   'word': 'Europe',
   'start': 627,
   'end': 633}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9527798),
   'word': 'Warsaw',
   'start': 0,
   'end': 6},
  {'entity_group': 'MISC',
   'score': np.float32(0.95895284),
   'word': '-',
   'start': 6,
   'end': 7},
  {'entity_group': 'MISC',
   'score': np.float32(0.94397974),
   'word': 'based',
   'start': 7,
   'end': 12},
  {'entity_group': 'MISC',

In [34]:
df_DistilBERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_DistilBERT)
    for entity in entities
])

df_DistilBERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",MISC,0.539408,Zapad,0,5
1,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",MISC,0.839036,Russian,12,19
2,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",MISC,0.705406,English,33,40
3,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",LOC,0.740974,West,42,46
4,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",LOC,0.966119,Russian Federation,116,134
...,...,...,...,...,...,...,...,...
170,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,MISC,0.943980,based,7,12
171,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,MISC,0.993857,Belarusian,13,23
172,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,PER,0.999114,Andrej Sannikau,56,71
173,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,LOC,0.503009,Zapad,89,94
174,Zapad 2021,21,List of Zapad exercises,MISC,0.891008,Zapad,8,13

#### BERT

In [35]:
MODEL_BERT = "dslim/bert-base-NER"

ner_BERT = pipeline(
    "ner",
    model=MODEL_BERT,
    aggregation_strategy="average",
    device=0 if torch.cuda.is_available() else -1
)

print("Model device:", ner_BERT.device)

ner_BERT

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 560.97it/s]
[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  |
bert.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Model device: cuda:0

TokenClassificationPipeline: {'model': 'BertForTokenClassification', 'dtype': 'float32', 'device': 'cuda', 'input_modalities': 'text'}

In [36]:
output_BERT = ner_BERT(data_processed[example])
output_BERT

[[{'entity_group': 'MISC',
   'score': np.float32(0.39069656),
   'word': 'Zapad',
   'start': 0,
   'end': 5},
  {'entity_group': 'MISC',
   'score': np.float32(0.99676335),
   'word': 'Russian',
   'start': 12,
   'end': 19},
  {'entity_group': 'LOC',
   'score': np.float32(0.457594),
   'word': 'West',
   'start': 42,
   'end': 46},
  {'entity_group': 'LOC',
   'score': np.float32(0.99949753),
   'word': 'Russian Federation',
   'start': 116,
   'end': 134},
  {'entity_group': 'LOC',
   'score': np.float32(0.99979705),
   'word': 'Belarus',
   'start': 139,
   'end': 146},
  {'entity_group': 'ORG',
   'score': np.float32(0.9896689),
   'word': 'Ministry of Defence of the Russian',
   'start': 212,
   'end': 246},
  {'entity_group': 'LOC',
   'score': np.float32(0.961596),
   'word': 'Federation',
   'start': 247,
   'end': 257}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997856),
   'word': 'Russian',
   'start': 66,
   'end': 73},
  {'entity_group': 'LOC',
   'score': np.float32(0.99982625),
   'word': 'Ukraine',
   'start': 117,
   'end': 124}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.9998246),
   'word': 'Belarus',
   'start': 28,
   'end': 35},
  {'entity_group': 'LOC',
   'score': np.float32(0.9998093),
   'word': 'Russia',
   'start': 40,
   'end': 46},
  {'entity_group': 'MISC',
   'score': np.float32(0.99971133),
   'word': 'Russian',
   'start': 109,
   'end': 116},
  {'entity_group': 'PER',
   'score': np.float32(0.99910533),
   'word': 'Dmitry Medvedev',
   'start': 127,
   'end': 142},
  {'entity_group': 'MISC',
   'score': np.float32(0.9995815),
   'word': 'Belarusian',
   'start': 147,
   'end': 157},
  {'entity_group': 'PER',
   'score': np.float32(0.9981865),
   'word': 'Alexander Lukashenko',
   'start': 168,
   'end': 188},
  {'entity_group': 'ORG',
   'score': np.float32(0.9984765),
   'word': 'Collective Rapid Reaction Forces',
   'start': 248,
   'end': 280},
  {'entity_group': 'ORG',
   'score': np.float32(0.49967927),
   'word': 'CSTO',
   'start': 288,
   'end': 292}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.94971657),
   'word': 'Republic of Belarus',
   'start': 53,
   'end': 72},
  {'entity_group': 'PER',
   'score': np.float32(0.99868524),
   'word': 'Viktor Gulevich',
   'start': 88,
   'end': 103},
  {'entity_group': 'LOC',
   'score': np.float32(0.3638667),
   'word': 'Zapad',
   'start': 106,
   'end': 111},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997093),
   'word': 'European',
   'start': 194,
   'end': 202},
  {'entity_group': 'LOC',
   'score': np.float32(0.30061197),
   'word': 'Zapad',
   'start': 267,
   'end': 272},
  {'entity_group': 'LOC',
   'score': np.float32(0.99973637),
   'word': 'Belarus',
   'start': 367,
   'end': 374},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997726),
   'word': 'Russia',
   'start': 379,
   'end': 385},
  {'entity_group': 'MISC',
   'score': np.float32(0.9793956),
   'word': 'Eastern European',
   'start': 524,
   'end': 540}],
 [{'entity_group': 'ORG',
   'score': np.float32(0.9814588),
   'word': 'General Staff',
   'start': 41,
   'end': 54},
  {'entity_group': 'LOC',
   'score': np.float32(0.9862229),
   'word': 'Southern Military District',
   'start': 176,
   'end': 202}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.99968874),
   'word': 'Belarusian',
   'start': 28,
   'end': 38},
  {'entity_group': 'LOC',
   'score': np.float32(0.65708995),
   'word': 'Obuz',
   'start': 93,
   'end': 97},
  {'entity_group': 'LOC',
   'score': np.float32(0.72404224),
   'word': 'Lesnovsky',
   'start': 98,
   'end': 107},
  {'entity_group': 'ORG',
   'score': np.float32(0.99047095),
   'word': 'Air Force',
   'start': 143,
   'end': 152},
  {'entity_group': 'ORG',
   'score': np.float32(0.9028551),
   'word': 'Air Defense forces',
   'start': 157,
   'end': 175},
  {'entity_group': 'LOC',
   'score': np.float32(0.64024204),
   'word': 'Domanovsky',
   'start': 177,
   'end': 187},
  {'entity_group': 'LOC',
   'score': np.float32(0.5659043),
   'word': 'Ruzhansky',
   'start': 226,
   'end': 235},
  {'entity_group': 'LOC',
   'score': np.float32(0.9963889),
   'word': 'Brest',
   'start': 246,
   'end': 251},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997445),
   'word': 'Russian',
   'start': 282,
   'end': 289},
  {'entity_group': 'LOC',
   'score': np.float32(0.5769284),
   'word': 'Kirillovsky',
   'start': 308,
   'end': 319},
  {'entity_group': 'LOC',
   'score': np.float32(0.8095472),
   'word': 'Strugi Krasnye',
   'start': 321,
   'end': 335},
  {'entity_group': 'LOC',
   'score': np.float32(0.49915946),
   'word': 'Mulino',
   'start': 337,
   'end': 343},
  {'entity_group': 'LOC',
   'score': np.float32(0.65605146),
   'word': 'Pogonovo',
   'start': 345,
   'end': 353},
  {'entity_group': 'LOC',
   'score': np.float32(0.77466106),
   'word': 'Khmelevka',
   'start': 355,
   'end': 364},
  {'entity_group': 'LOC',
   'score': np.float32(0.71958953),
   'word': 'Pravdinsky',
   'start': 366,
   'end': 376},
  {'entity_group': 'LOC',
   'score': np.float32(0.78821945),
   'word': 'Dobrovolsky',
   'start': 378,
   'end': 389},
  {'entity_group': 'LOC',
   'score': np.float32(0.79090905),
   'word': 'Dorogobuzh',
   'start': 391,
   'end': 401},
  {'entity_group': 'LOC',
   'score': np.float32(0.49654645),
   'word': 'Volsky',
   'start': 403,
   'end': 409}],
 [],
 [{'entity_group': 'MISC',
   'score': np.float32(0.82198805),
   'word': 'Uran - 9',
   'start': 148,
   'end': 154},
  {'entity_group': 'MISC',
   'score': np.float32(0.2811221),
   'word': 'Nerekhta',
   'start': 158,
   'end': 166}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.999589),
   'word': 'Belarusian',
   'start': 18,
   'end': 28},
  {'entity_group': 'LOC',
   'score': np.float32(0.99977094),
   'word': 'Russia',
   'start': 89,
   'end': 95},
  {'entity_group': 'ORG',
   'score': np.float32(0.9979847),
   'word': 'Ministry of Defense of the Republic of Belarus',
   'start': 101,
   'end': 147}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.59564203),
   'word': 'Kirilovsky',
   'start': 295,
   'end': 305},
  {'entity_group': 'LOC',
   'score': np.float32(0.7780746),
   'word': 'Strugi Krasnye',
   'start': 307,
   'end': 321},
  {'entity_group': 'LOC',
   'score': np.float32(0.5043638),
   'word': 'Mulino',
   'start': 323,
   'end': 329},
  {'entity_group': 'LOC',
   'score': np.float32(0.6480655),
   'word': 'Pogonovo',
   'start': 331,
   'end': 339},
  {'entity_group': 'LOC',
   'score': np.float32(0.77348274),
   'word': 'Khmelevka',
   'start': 341,
   'end': 350},
  {'entity_group': 'LOC',
   'score': np.float32(0.67839634),
   'word': 'Pravdinsky',
   'start': 352,
   'end': 362},
  {'entity_group': 'LOC',
   'score': np.float32(0.7864865),
   'word': 'Dobrovolsky',
   'start': 364,
   'end': 375},
  {'entity_group': 'LOC',
   'score': np.float32(0.7896922),
   'word': 'Dorogobuzh',
   'start': 377,
   'end': 387},
  {'entity_group': 'LOC',
   'score': np.float32(0.4996384),
   'word': 'Volsky',
   'start': 393,
   'end': 399},
  {'entity_group': 'LOC',
   'score': np.float32(0.9993454),
   'word': 'Russian Federation',
   'start': 433,
   'end': 451},
  {'entity_group': 'LOC',
   'score': np.float32(0.9990575),
   'word': 'Baltic Sea',
   'start': 460,
   'end': 470},
  {'entity_group': 'LOC',
   'score': np.float32(0.9976246),
   'word': 'Republic of Belarus',
   'start': 505,
   'end': 524},
  {'entity_group': 'LOC',
   'score': np.float32(0.8542695),
   'word': 'Obuz - Lesnovsky',
   'start': 527,
   'end': 541},
  {'entity_group': 'LOC',
   'score': np.float32(0.99494714),
   'word': 'Brest',
   'start': 543,
   'end': 548},
  {'entity_group': 'LOC',
   'score': np.float32(0.7336374),
   'word': 'Chepelevo',
   'start': 550,
   'end': 559},
  {'entity_group': 'LOC',
   'score': np.float32(0.6600676),
   'word': 'Domanovsky',
   'start': 561,
   'end': 571},
  {'entity_group': 'LOC',
   'score': np.float32(0.5770336),
   'word': 'Ruzhansky',
   'start': 577,
   'end': 586},
  {'entity_group': 'LOC',
   'score': np.float32(0.51225704),
   'word': 'Mulino',
   'start': 631,
   'end': 637},
  {'entity_group': 'LOC',
   'score': np.float32(0.8717889),
   'word': 'Nizhny Novgorod',
   'start': 643,
   'end': 658}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.55916315),
   'word': 'Zapad',
   'start': 28,
   'end': 33},
  {'entity_group': 'MISC',
   'score': np.float32(0.9482889),
   'word': '2021',
   'start': 34,
   'end': 38}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.35728896),
   'word': 'Msta',
   'start': 102,
   'end': 106},
  {'entity_group': 'MISC',
   'score': np.float32(0.5549148),
   'word': 'S',
   'start': 107,
   'end': 108},
  {'entity_group': 'ORG',
   'score': np.float32(0.4601453),
   'word': 'Fire Shaft',
   'start': 136,
   'end': 146}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.7720579),
   'word': 'Kaliningrad Oblast',
   'start': 31,
   'end': 49},
  {'entity_group': 'MISC',
   'score': np.float32(0.9965168),
   'word': 'Platform',
   'start': 235,
   'end': 243},
  {'entity_group': 'MISC',
   'score': np.float32(0.886008),
   'word': 'M',
   'start': 244,
   'end': 245},
  {'entity_group': 'MISC',
   'score': np.float32(0.70680404),
   'word': 'Kalashnikov',
   'start': 337,
   'end': 348}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9984571),
   'word': 'T',
   'start': 0,
   'end': 1},
  {'entity_group': 'MISC',
   'score': np.float32(0.44126192),
   'word': 'Terminator',
   'start': 95,
   'end': 105},
  {'entity_group': 'MISC',
   'score': np.float32(0.9044748),
   'word': 'B - 19',
   'start': 193,
   'end': 197},
  {'entity_group': 'MISC',
   'score': np.float32(0.73892325),
   'word': 'TOS - 1A',
   'start': 324,
   'end': 330},
  {'entity_group': 'ORG',
   'score': np.float32(0.66032577),
   'word': 'Solntsepek',
   'start': 332,
   'end': 342}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.52171004),
   'word': 'Uran',
   'start': 208,
   'end': 212},
  {'entity_group': 'MISC',
   'score': np.float32(0.30356133),
   'word': 'Nerekhta',
   'start': 397,
   'end': 405}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.6507846),
   'word': 'Sagittarius',
   'start': 195,
   'end': 206}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9199479),
   'word': 'Su - 35S',
   'start': 62,
   'end': 68},
  {'entity_group': 'MISC',
   'score': np.float32(0.94985193),
   'word': 'Su - 30SM',
   'start': 70,
   'end': 77},
  {'entity_group': 'MISC',
   'score': np.float32(0.9565129),
   'word': 'MiG - 31BM',
   'start': 79,
   'end': 87},
  {'entity_group': 'MISC',
   'score': np.float32(0.97664785),
   'word': 'Su - 34',
   'start': 93,
   'end': 98},
  {'entity_group': 'MISC',
   'score': np.float32(0.9240463),
   'word': 'Mi -',
   'start': 193,
   'end': 196},
  {'entity_group': 'MISC',
   'score': np.float32(0.92944527),
   'word': 'Mi - 28',
   'start': 226,
   'end': 231},
  {'entity_group': 'MISC',
   'score': np.float32(0.94011414),
   'word': 'Night Hunter',
   'start': 233,
   'end': 245},
  {'entity_group': 'MISC',
   'score': np.float32(0.94108725),
   'word': 'Ka - 52',
   'start': 255,
   'end': 260},
  {'entity_group': 'MISC',
   'score': np.float32(0.5936404),
   'word': 'Alligator',
   'start': 262,
   'end': 271},
  {'entity_group': 'MISC',
   'score': np.float32(0.9605287),
   'word': 'Mi -',
   'start': 278,
   'end': 281},
  {'entity_group': 'MISC',
   'score': np.float32(0.83364487),
   'word': 'Su - 34S',
   'start': 458,
   'end': 464}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.43110973),
   'word': 'Mulino',
   'start': 66,
   'end': 72},
  {'entity_group': 'LOC',
   'score': np.float32(0.8688241),
   'word': 'Nizhny Novgorod',
   'start': 92,
   'end': 107}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9996933),
   'word': 'European',
   'start': 124,
   'end': 132},
  {'entity_group': 'MISC',
   'score': np.float32(0.99911386),
   'word': 'NATO',
   'start': 143,
   'end': 147},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997689),
   'word': 'Russian',
   'start': 198,
   'end': 205},
  {'entity_group': 'MISC',
   'score': np.float32(0.99967635),
   'word': 'Belarusian',
   'start': 210,
   'end': 220},
  {'entity_group': 'LOC',
   'score': np.float32(0.70916605),
   'word': 'Neris',
   'start': 249,
   'end': 254},
  {'entity_group': 'MISC',
   'score': np.float32(0.99963486),
   'word': 'Lithuanian',
   'start': 258,
   'end': 268},
  {'entity_group': 'LOC',
   'score': np.float32(0.8108185),
   'word': 'Pomoria',
   'start': 277,
   'end': 284},
  {'entity_group': 'LOC',
   'score': np.float32(0.9844327),
   'word': 'Polar Republic',
   'start': 289,
   'end': 303},
  {'entity_group': 'LOC',
   'score': np.float32(0.99981207),
   'word': 'Belarus',
   'start': 366,
   'end': 373},
  {'entity_group': 'MISC',
   'score': np.float32(0.9996973),
   'word': 'Belarusian',
   'start': 420,
   'end': 430},
  {'entity_group': 'MISC',
   'score': np.float32(0.9277367),
   'word': 'Russian',
   'start': 431,
   'end': 438}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9997757),
   'word': 'American',
   'start': 13,
   'end': 21},
  {'entity_group': 'ORG',
   'score': np.float32(0.9918067),
   'word': 'Joint Chiefs of Staff',
   'start': 50,
   'end': 71},
  {'entity_group': 'PER',
   'score': np.float32(0.99955934),
   'word': 'Mark Milley',
   'start': 72,
   'end': 83},
  {'entity_group': 'MISC',
   'score': np.float32(0.63458914),
   'word': 'Zapad',
   'start': 101,
   'end': 106},
  {'entity_group': 'MISC',
   'score': np.float32(0.99977463),
   'word': 'American',
   'start': 123,
   'end': 131},
  {'entity_group': 'MISC',
   'score': np.float32(0.99979144),
   'word': 'Russian',
   'start': 172,
   'end': 179},
  {'entity_group': 'LOC',
   'score': np.float32(0.99981755),
   'word': 'Ukraine',
   'start': 192,
   'end': 199},
  {'entity_group': 'PER',
   'score': np.float32(0.5139325),
   'word': 'Milley',
   'start': 353,
   'end': 359},
  {'entity_group': 'MISC',
   'score': np.float32(0.99978846),
   'word': 'American',
   'start': 381,
   'end': 389},
  {'entity_group': 'PER',
   'score': np.float32(0.9029756),
   'word': 'Joe Biden',
   'start': 400,
   'end': 409},
  {'entity_group': 'MISC',
   'score': np.float32(0.9997745),
   'word': 'Russian',
   'start': 436,
   'end': 443},
  {'entity_group': 'LOC',
   'score': np.float32(0.99980325),
   'word': 'Ukraine',
   'start': 459,
   'end': 466},
  {'entity_group': 'PER',
   'score': np.float32(0.5147542),
   'word': 'Milley',
   'start': 468,
   'end': 474},
  {'entity_group': 'MISC',
   'score': np.float32(0.59422904),
   'word': 'Russian',
   'start': 525,
   'end': 532},
  {'entity_group': 'ORG',
   'score': np.float32(0.81008136),
   'word': 'Armed Forces',
   'start': 533,
   'end': 545},
  {'entity_group': 'PER',
   'score': np.float32(0.90298235),
   'word': 'Valery Gerasimov',
   'start': 547,
   'end': 563},
  {'entity_group': 'LOC',
   'score': np.float32(0.9998018),
   'word': 'Finland',
   'start': 568,
   'end': 575},
  {'entity_group': 'LOC',
   'score': np.float32(0.9997485),
   'word': 'Europe',
   'start': 627,
   'end': 633}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.9993062),
   'word': 'Belarusian',
   'start': 13,
   'end': 23},
  {'entity_group': 'PER',
   'score': np.float32(0.9634141),
   'word': 'Andrej Sannikau',
   'start': 56,
   'end': 71},
  {'entity_group': 'MISC',
   'score': np.float32(0.5642881),
   'word': 'Zapad',
   'start': 89,
   'end': 94}],
 [{'entity_group': 'MISC',
   'score': np.float32(0.5588191),
   'word': 'Zapad',
   'start': 8,
   'end': 13}]]

In [37]:
df_BERT = pd.DataFrame([
    {
        "page": example,
        "paragraph_id": paragraph_id,
        "paragraph": data_processed[example][paragraph_id],
        **entity
    }
    for paragraph_id, entities in enumerate(output_BERT)
    for entity in entities
])

df_BERT

,page,paragraph_id,paragraph,entity_group,score,word,start,end
0,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",MISC,0.390697,Zapad,0,5
1,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",MISC,0.996763,Russian,12,19
2,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",LOC,0.457594,West,42,46
3,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",LOC,0.999498,Russian Federation,116,134
4,Zapad 2021,0,"Zapad 2021 (Russian: Запад-2021, English: West...",LOC,0.999797,Belarus,139,146
...,...,...,...,...,...,...,...,...
127,Zapad 2021,19,According to American General and Chairman of ...,LOC,0.999749,Europe,627,633
128,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,MISC,0.999306,Belarusian,13,23
129,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,PER,0.963414,Andrej Sannikau,56,71
130,Zapad 2021,20,Warsaw-based Belarusian former politician and ...,MISC,0.564288,Zapad,89,94
131,Zapad 2021,21,List of Zapad exercises,MISC,0.558819,Zapad,8,13

### Model testing and evaluation (done on 10% of the data)

#### subset creation

create a 10% subset to evalute the models on the data.

In [38]:
all_pages = list(data_processed.keys())

if not all_pages:
    raise ValueError("data_processed contains no pages.")

sample_size = max(1, math.ceil(len(all_pages) * 0.10))

evaluation_pages = (
    pd.Series(all_pages)
    .sample(n=sample_size, random_state=42)
    .tolist()
)

evaluation_data = {
    page: data_processed[page]
    for page in evaluation_pages
}

print(f"Sampled {sample_size} of {len(all_pages)} pages.")

Sampled 90 of 897 pages.

#### DistilBERT

In [39]:

BATCH_SIZE = 32 if ner_DistilBERT.device.type == "cuda" else 1

# Keep each paragraph paired with its original page and paragraph ID.
paragraph_records = [
    (page, paragraph_id, paragraph)
    for page, paragraphs in evaluation_data.items()
    for paragraph_id, paragraph in enumerate(paragraphs)
]

rows = []
started = time.perf_counter()

# Stream paragraphs through the model in batches.
predictions = ner_DistilBERT(
    (record[2] for record in paragraph_records),
    batch_size=BATCH_SIZE,
    num_workers=0
)

for (page, paragraph_id, paragraph), entities in tqdm(
    zip(paragraph_records, predictions, strict=True),
    total=len(paragraph_records),
    desc="DistilBERT NER",
    unit="paragraph"
):
    for entity in entities:
        rows.append({
            "entity_group": entity["entity_group"],
            "score": entity["score"],
            "word": entity["word"],
            "start": entity["start"],
            "end": entity["end"],
            "Source": page,
            "Index": paragraph_id,
            "Text": paragraph
        })

elapsed = time.perf_counter() - started

columns = [
    "entity_group",
    "score",
    "word",
    "start",
    "end",
    "Source",
    "Index",
    "Text"
]

df_DistilBERT_10pct = pd.DataFrame(rows, columns=columns)

output_dir = os.path.join(
    "NER_output",
    "model_testing_and_evaluation"
)
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(
    output_dir,
    "post_NER_DistilBERT_10pct.csv"
)

df_DistilBERT_10pct.to_csv(output_path, index=False)

print(
    f"Processed {len(evaluation_data)} sampled pages "
    f"and {len(paragraph_records)} paragraphs in {elapsed:.1f} seconds."
)
print(f"Batch size: {BATCH_SIZE}")
print(f"Saved {len(df_DistilBERT_10pct)} entity rows to: {output_path}")

df_DistilBERT_10pct.head()

DistilBERT NER: 100%|██████████| 4746/4746 [00:43<00:00, 108.76paragraph/s]

Processed 90 sampled pages and 4746 paragraphs in 43.6 seconds.
Batch size: 32
Saved 35222 entity rows to: NER_output\model_testing_and_evaluation\post_NER_DistilBERT_10pct.csv

,entity_group,score,word,start,end,Source,Index,Text
0,MISC,0.687287,Investment,57,67,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
1,MISC,0.496020,Services,83,91,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
2,LOC,0.797773,Russian Federation,99,117,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
3,MISC,0.647296,Russian,143,150,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
4,ORG,0.770204,Federation,151,161,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."

#### BERT

In [40]:
BATCH_SIZE = 32 if ner_BERT.device.type == "cuda" else 1

# Keep each paragraph paired with its original page and paragraph ID.
paragraph_records = [
    (page, paragraph_id, paragraph)
    for page, paragraphs in evaluation_data.items()
    for paragraph_id, paragraph in enumerate(paragraphs)
]

rows = []
started = time.perf_counter()

# Stream paragraphs through the model in batches.
predictions = ner_BERT(
    (record[2] for record in paragraph_records),
    batch_size=BATCH_SIZE,
    num_workers=0
)

for (page, paragraph_id, paragraph), entities in tqdm(
    zip(paragraph_records, predictions, strict=True),
    total=len(paragraph_records),
    desc="BERT NER",
    unit="paragraph"
):
    for entity in entities:
        rows.append({
            "entity_group": entity["entity_group"],
            "score": entity["score"],
            "word": entity["word"],
            "start": entity["start"],
            "end": entity["end"],
            "Source": page,
            "Index": paragraph_id,
            "Text": paragraph
        })

elapsed = time.perf_counter() - started

columns = [
    "entity_group",
    "score",
    "word",
    "start",
    "end",
    "Source",
    "Index",
    "Text"
]

df_BERT_10pct = pd.DataFrame(rows, columns=columns)

output_dir = os.path.join(
    "NER_output",
    "model_testing_and_evaluation"
)
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(
    output_dir,
    "post_NER_BERT_10pct.csv"
)

df_BERT_10pct.to_csv(output_path, index=False)

print(
    f"Processed {len(evaluation_data)} sampled pages "
    f"and {len(paragraph_records)} paragraphs in {elapsed:.1f} seconds."
)
print(f"Batch size: {BATCH_SIZE}")
print(f"Saved {len(df_BERT_10pct)} entity rows to: {output_path}")

df_BERT_10pct.head()

BERT NER: 100%|██████████| 4746/4746 [00:49<00:00, 96.68paragraph/s]

Processed 90 sampled pages and 4746 paragraphs in 49.1 seconds.
Batch size: 32
Saved 32663 entity rows to: NER_output\model_testing_and_evaluation\post_NER_BERT_10pct.csv

,entity_group,score,word,start,end,Source,Index,Text
0,LOC,0.999146,Russian Federation,99,117,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
1,MISC,0.788013,Russian,143,150,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
2,LOC,0.608827,Federation,151,161,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
3,LOC,0.909937,U. S.,245,249,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."
4,PER,0.964426,Joe Biden,260,269,Executive Order 14071,0,"Executive Order 14071, officially titled Prohi..."

### Full Data

Apply the chosen NER to the data, done post evaluation and improvement changes (improvement stage pending 11.10.26)

(currently DistilBert pending models evaluations)
date: 05.10.26

In [41]:
BATCH_SIZE = 32 if ner_DistilBERT.device.type == "cuda" else 1

# Use the full dataset.
paragraph_records = [
    (page, paragraph_id, paragraph)
    for page, paragraphs in data_processed.items()
    for paragraph_id, paragraph in enumerate(paragraphs)
]

rows = []
started = time.perf_counter()

predictions = ner_DistilBERT(
    (record[2] for record in paragraph_records),
    batch_size=BATCH_SIZE,
    num_workers=0
)

for (page, paragraph_id, paragraph), entities in tqdm(
    zip(paragraph_records, predictions, strict=True),
    total=len(paragraph_records),
    desc="DistilBERT NER — full data",
    unit="paragraph"
):
    for entity in entities:
        rows.append({
            "entity_group": entity["entity_group"],
            "score": entity["score"],
            "word": entity["word"],
            "start": entity["start"],
            "end": entity["end"],
            "Source": page,
            "Index": paragraph_id,
            "Text": paragraph
        })

elapsed = time.perf_counter() - started

columns = [
    "entity_group",
    "score",
    "word",
    "start",
    "end",
    "Source",
    "Index",
    "Text"
]

df_DistilBERT = pd.DataFrame(rows, columns=columns)

output_dir = "NER_output"
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(output_dir, "post_NER.csv")
df_DistilBERT.to_csv(output_path, index=False)

print(
    f"Processed {len(data_processed)} pages "
    f"and {len(paragraph_records)} paragraphs in {elapsed:.1f} seconds."
)
print(f"Model device: {ner_DistilBERT.device}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Saved {len(df_DistilBERT)} entity rows to {output_path}")

DistilBERT NER — full data: 100%|██████████| 42822/42822 [06:13<00:00, 114.74paragraph/s]

Processed 897 pages and 42822 paragraphs in 373.2 seconds.
Model device: cuda:0
Batch size: 32
Saved 301525 entity rows to NER_output\post_NER.csv

In [45]:
MAX_BYTES = 90 * 1024 * 1024

source = Path(REPO_PATH) / "NER_output" / "post_NER.csv"
parts_dir = source.parent / "post_NER_parts"
parts_dir.mkdir(parents=True, exist_ok=True)

# Allow long text fields.
csv.field_size_limit(2**31 - 1)

def encode_row(row):
    buffer = io.StringIO()
    csv.writer(buffer, lineterminator="\n").writerow(row)
    return buffer.getvalue().encode("utf-8")

with source.open("r", encoding="utf-8", newline="") as f:
    reader = csv.reader(f)
    header = encode_row(next(reader))

    # Remove parts from an earlier run.
    for old_part in parts_dir.glob("part_*.csv"):
        old_part.unlink()

    part_number = 1
    output = (parts_dir / f"part_{part_number:04d}.csv").open("wb")
    output.write(header)
    current_size = len(header)
    row_count = 0

    try:
        for row in reader:
            encoded = encode_row(row)

            if len(header) + len(encoded) > MAX_BYTES:
                raise ValueError("A single CSV row exceeds the part size limit.")

            if current_size + len(encoded) > MAX_BYTES:
                output.close()
                part_number += 1
                output = (
                    parts_dir / f"part_{part_number:04d}.csv"
                ).open("wb")
                output.write(header)
                current_size = len(header)

            output.write(encoded)
            current_size += len(encoded)
            row_count += 1
    finally:
        output.close()

print(f"Saved {row_count} entity rows across {part_number} CSV parts.")
for part in sorted(parts_dir.glob("part_*.csv")):
    print(f"{part.name}: {part.stat().st_size / 1024**2:.2f} MiB")

Saved 301525 entity rows across 2 CSV parts.
part_0001.csv: 90.00 MiB
part_0002.csv: 87.99 MiB

## Commit to repo

In [46]:
GITHUB_USER = "idoschw3"
GITHUB_REPO = "Corpus2GeoRAG"
GITHUB_EMAIL = "193781032+idoschw3@users.noreply.github.com"
COMMIT_MESSAGE = "Update NER workflow"

LOCAL_REPO_PATH = Path.home() / GITHUB_REPO
MAX_GIT_FILE_BYTES = 100 * 1024 * 1024

# --------------------------------------------------
# Detect runtime
# --------------------------------------------------

if os.name == "nt":
    IS_LOCAL = True
elif os.environ.get("COLAB_RELEASE_TAG"):
    IS_LOCAL = False
else:
    raise RuntimeError(
        "Could not identify this runtime as Windows or a hosted Colab VM."
    )

if shutil.which("git") is None:
    raise RuntimeError(
        "Git is not available to this Jupyter environment. "
        "Install Git for Windows and restart Jupyter if running locally."
    )

# --------------------------------------------------
# Locate the repository
# --------------------------------------------------

if IS_LOCAL:
    candidates = [Path.cwd(), LOCAL_REPO_PATH]

    previous_repo_path = globals().get("REPO_PATH")
    if previous_repo_path:
        candidates.insert(0, Path(previous_repo_path))

    detected_repo = None

    for candidate in candidates:
        if not candidate.is_dir():
            continue

        probe = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            cwd=candidate,
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True
        )

        if probe.returncode == 0:
            root = Path(probe.stdout.strip()).resolve()

            if root.name.lower() == GITHUB_REPO.lower():
                detected_repo = root
                break

    if detected_repo is None:
        raise FileNotFoundError(
            f"Could not find your local {GITHUB_REPO} checkout.\n"
            f"Clone it to {LOCAL_REPO_PATH}, or update LOCAL_REPO_PATH."
        )

    REPO_PATH = str(detected_repo)

else:
    REPO_PATH = f"/content/{GITHUB_REPO}"

    if not Path(REPO_PATH).is_dir():
        raise FileNotFoundError(
            f"{REPO_PATH} does not exist. Run your clone cell first."
        )

os.chdir(REPO_PATH)

print("Runtime:", "Local Windows" if IS_LOCAL else "Colab VM")
print("Repository:", REPO_PATH)


def run_git(args, *, env=None, show_output=True):
    """Run Git and include its actual output if it fails."""
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_PATH,
        env=env,
        stdin=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True
    )

    if show_output:
        if result.stdout:
            print(result.stdout, end="")
        if result.stderr:
            print(result.stderr, end="")

    if result.returncode != 0:
        details = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(f"git {' '.join(args)} failed:\n{details}")

    return result


# --------------------------------------------------
# Git configuration
# --------------------------------------------------

run_git(["config", "user.name", GITHUB_USER])
run_git(["config", "user.email", GITHUB_EMAIL])
run_git([
    "remote", "set-url", "origin",
    f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}.git"
])

branch = run_git(
    ["branch", "--show-current"],
    show_output=False
).stdout.strip()

if not branch:
    raise RuntimeError("Could not determine the current Git branch.")

print("Branch:", branch)

# Stop if an earlier rebase or merge is still paused.
for state_path in ("rebase-merge", "rebase-apply", "MERGE_HEAD"):
    git_state = run_git(
        ["rev-parse", "--git-path", state_path],
        show_output=False
    ).stdout.strip()

    if Path(git_state).exists():
        raise RuntimeError(
            "An earlier rebase or merge is still in progress. "
            "Check `git status` and resolve it before rerunning this cell."
        )

# --------------------------------------------------
# Authentication and synchronization
# --------------------------------------------------

git_env = os.environ.copy()
git_env["GIT_TERMINAL_PROMPT"] = "0"

auth_options = []
askpass_dir = None

try:
    if IS_LOCAL:
        # Use Git credentials already configured on your computer.
        print("Authentication: local Git credentials.")

    else:
        from google.colab import userdata

        github_token = userdata.get("GITHUB_TOKEN")

        if not github_token:
            raise ValueError(
                "GITHUB_TOKEN is missing from Colab Secrets. "
                "Add it and enable notebook access."
            )

        askpass_dir = tempfile.TemporaryDirectory(
            prefix="github-askpass-"
        )
        askpass_path = Path(askpass_dir.name) / "askpass.sh"

        askpass_path.write_text(
            "#!/bin/sh\n"
            'case "$1" in\n'
            '  *Username*) printf "%s\\n" "$GITHUB_USER" ;;\n'
            '  *Password*) printf "%s\\n" "$GITHUB_TOKEN" ;;\n'
            "esac\n",
            encoding="utf-8"
        )
        askpass_path.chmod(0o700)

        git_env["GITHUB_USER"] = GITHUB_USER
        git_env["GITHUB_TOKEN"] = github_token
        git_env["GIT_ASKPASS"] = str(askpass_path)

        auth_options = ["-c", "credential.helper="]

        print("Authentication: Colab GITHUB_TOKEN Secret.")

    # --------------------------------------------------
    # Prevent accidental nested repository
    # --------------------------------------------------

    ignore_entry = f"/{GITHUB_REPO}/"
    gitignore_path = Path(REPO_PATH) / ".gitignore"

    existing_ignore = (
        gitignore_path.read_text(encoding="utf-8")
        if gitignore_path.exists()
        else ""
    )

    if ignore_entry not in existing_ignore.splitlines():
        with gitignore_path.open("a", encoding="utf-8") as f:
            if existing_ignore and not existing_ignore.endswith("\n"):
                f.write("\n")
            f.write(ignore_entry + "\n")

    nested_repo = run_git(
        ["ls-files", "--stage", "--", GITHUB_REPO],
        show_output=False
    ).stdout.strip()

    if nested_repo:
        run_git([
            "rm", "--cached", "-r", "-f", "--", GITHUB_REPO
        ])
        print("Removed the nested repository path from Git tracking.")

    # --------------------------------------------------
    # Find files exceeding GitHub's per-file limit
    # --------------------------------------------------

    candidate_files = run_git(
        [
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "-z"
        ],
        show_output=False
    ).stdout.split("\0")

    excluded_files = set()

    for relative_path in sorted(set(candidate_files) - {""}):
        file_path = Path(REPO_PATH) / relative_path

        if not file_path.is_file():
            continue

        file_size = file_path.stat().st_size

        if file_size > MAX_GIT_FILE_BYTES:
            excluded_files.add(relative_path)

            # Remove from Git's index, while keeping the file on disk.
            run_git(
                [
                    "rm",
                    "--cached",
                    "--ignore-unmatch",
                    "-f",
                    "--",
                    f":(top,literal){relative_path}"
                ],
                show_output=False
            )

            print(
                f"Excluded oversized file: {relative_path} "
                f"({file_size / 1024**2:.2f} MiB). "
                "Kept on disk."
            )

    # --------------------------------------------------
    # Stage changes, excluding oversized files
    # --------------------------------------------------

    exclusion_pathspecs = [
        f":(top,literal,exclude){path}"
        for path in sorted(excluded_files)
    ]

    run_git(["add", "-A", "--", ".", *exclusion_pathspecs])

    # Exclude notebook copies, preserving the original cell's behavior.
    staged_files = run_git(
        ["diff", "--cached", "--name-only", "-z"],
        show_output=False
    ).stdout.split("\0")

    for notebook in staged_files:
        if (
            notebook.endswith(".ipynb")
            and notebook not in excluded_files
        ):
            run_git([
                "restore", "--staged", "--",
                f":(top,literal){notebook}"
            ])

    # --------------------------------------------------
    # Create a normal commit
    # --------------------------------------------------

    staged_diff = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=REPO_PATH,
        stdin=subprocess.DEVNULL
    )

    if staged_diff.returncode == 1:
        run_git(["commit", "-m", COMMIT_MESSAGE])
        print("Repository changes committed.")
    elif staged_diff.returncode == 0:
        print("No new repository changes to commit.")
    else:
        raise RuntimeError("Could not check the staged changes.")

    # --------------------------------------------------
    # Restore tracked notebook copies on disk
    # This discards edits to those on-disk copies.
    # --------------------------------------------------

    tracked_files = run_git(
        ["ls-tree", "-r", "--name-only", "-z", "HEAD"],
        show_output=False
    ).stdout.split("\0")

    for notebook in tracked_files:
        if notebook.endswith(".ipynb"):
            run_git([
                "restore", "--worktree", "--",
                f":(top,literal){notebook}"
            ])

    # --------------------------------------------------
    # Pull/rebase GitHub changes
    # --------------------------------------------------

    pull = subprocess.run(
        ["git", *auth_options, "pull", "--rebase", "origin", branch],
        cwd=REPO_PATH,
        env=git_env,
        stdin=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True
    )

    if pull.stdout:
        print(pull.stdout, end="")
    if pull.stderr:
        print(pull.stderr, end="")

    if pull.returncode != 0:
        conflicted = run_git(
            ["diff", "--name-only", "--diff-filter=U"],
            show_output=False
        ).stdout.splitlines()

        if conflicted == [".gitignore"]:
            ours = run_git(
                ["show", ":2:.gitignore"],
                show_output=False
            ).stdout

            theirs = run_git(
                ["show", ":3:.gitignore"],
                show_output=False
            ).stdout

            if ours.strip() != theirs.strip():
                raise RuntimeError(
                    "The .gitignore versions differ. The rebase is paused; "
                    "inspect the conflict before continuing."
                )

            gitignore_path.write_text(
                ours + ("\n" if ours and not ours.endswith("\n") else ""),
                encoding="utf-8"
            )

            run_git(["add", "--", ".gitignore"])
            run_git([
                "-c", "core.editor=true", "rebase", "--continue"
            ])

        else:
            raise RuntimeError(
                "Pull failed. Check the Git output above and `git status`. "
                "If running locally, verify your GitHub authentication."
            )

    # --------------------------------------------------
    # Push synchronized changes
    # --------------------------------------------------

    run_git(
        [*auth_options, "push", "origin", branch],
        env=git_env
    )

    print(
        f"Successfully pushed to {GITHUB_USER}/{GITHUB_REPO} "
        f"on branch '{branch}'."
    )

finally:
    if askpass_dir is not None:
        askpass_dir.cleanup()

    git_env.pop("GITHUB_TOKEN", None)

Runtime: Local Windows
Repository: C:\Users\idosc\Corpus2GeoRAG
Branch: main
Authentication: local Git credentials.
Excluded oversized file: NER_output/post_NER.csv (178.28 MiB). Kept on disk.
warning: in the working copy of 'NER_output/post_NER_parts/part_0001.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'NER_output/post_NER_parts/part_0002.csv', LF will be replaced by CRLF the next time Git touches it
[main d0ccc0d] Update NER workflow
 2 files changed, 301527 insertions(+)
 create mode 100644 NER_output/post_NER_parts/part_0001.csv
 create mode 100644 NER_output/post_NER_parts/part_0002.csv
Repository changes committed.
Current branch main is up to date.
From https://github.com/idoschw3/Corpus2GeoRAG
 * branch            main       -> FETCH_HEAD
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File NER_output/post_NER_parts/part_0002.csv is 87.99 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File NER_output/post_NER_parts/part_0001.csv is 90.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/idoschw3/Corpus2GeoRAG.git
   1049f33..d0ccc0d  main -> main
Successfully pushed to idoschw3/Corpus2GeoRAG on branch 'main'.